Update branding to Si Cepat VPN and licensing check redirects

diff --git a/audit_menu/menu/Lt-on-off b/audit_menu/menu/Lt-on-off
--- a/audit_menu/menu/Lt-on-off
+++ b/audit_menu/menu/Lt-on-off
@@ -1,4 +1,182 @@
-#!/bin/bash
-z="
-";DKz='-9]$';jIz='"$CR';SMz='"Sel';lEz='N_ST';RDz='93m─';wBz='p Da';pJz='" me';kLz='f "$';WMz='ions';Gz='"\\0';nKz='| te';lDz='SSIO';FGz=' yan';QLz='hutd';LHz='pt C';oBz='t ht';rIz=' Lim';DIz='\b\b';PMz='Envi';yHz='$tem';sIz='it I';hHz='whil';cDz=' AUT';mKz='RY" ';WDz='m   ';UGz='*m//';dDz='OSCR';mCz='t -q';tJz='adin';CLz='RON_';FFz=' /et';DCz='/'\'')';KLz='succ';JFz='n)';ZGz='in_t';fGz='dth ';IKz='alid';OCz='_ip1';CDz=' ]];';bCz='n/ma';KJz=' a n';KIz='NC='\''';OBz='s://';jLz='rm -';GHz='- \0';bEz='me/6';Kz='\\03';QMz='ronm';fFz='ama ';EBz=''\'' '\'' ';UKz='IMIT';YBz='ya=$';vz='# " ';Oz='=$(c';Iz='2;1m';AIz='p"}';hEz='m\03';vLz='ment';SDz='────';hKz='bin:';PIz='LIMI';sGz='e "$';YFz='bari';XFz='ner(';pDz='33[0';AHz='akas';HJz='m Ju';AJz='D}[O';oEz='}';CGz='an p';QFz=' {';HEz='acce';gDz='""';dGz='=$((';nJz='(1-5';mGz='s}s%';jJz='inut';jGz='tf "';aDz='OT F';PBz='api.';sDz='[0;3';VMz=' Opt';bFz='g';nHz='null';Hz='33[3';uCz='prin';SJz=' min';Dz=') { ';IHz='3[0;';tFz='$1"';XHz='load';RLz='own ';QCz='//ra';YGz='#pla';MGz='cho ';kBz='inse';uJz='g $!';vJz='[ ! ';sz='ep -';DHz=' men';UFz='———\';rLz='nAct';RIz='_SCR';NFz='is_p';ECz='date';Yz='.\e[';vGz='atte';RFz='3[5;';Mz='"; }';TFz='————';PDz='"\03';wEz='isp)';Lz='3[0m';iCz=') {';dIz='ssh-';xz='c/bo';oLz='y \0';oKz='E" >';AKz='^[1-';cLz='enu"';Pz='at /';sEz='$(ca';JGz='l pl';ZEz='ps:/';LDz=']; t';lKz='n\n$';gz=' " "';HHz='xt1=';vBz=' gre';hBz='$(cu';tLz=' Env';ZDz='04 N';bJz='  1 ';JDz=' < $';GIz='e[92';NEz='crip';sHz='[%c]';JLz='32m ';rCz='aya ';Wz='oadi';mJz='ill ';xLz='3[35';NHz='t By';gGz='- le';Vz='32ml';ZJz='m 1 ';ALz=' dar';PGz='t" |';xKz='E"';lJz='utok';cGz='aces';HLz='Bann';hIz='tatu';bz='ID=$';dFz=';1m ';KKz='C}"';iKz='/sbi';cKz='=/us';MHz='redi';GJz='3[37';cMz='LY';mIz=' ]; ';CJz='{NC}';MJz='r in';rHz='n#?}';eBz='data';WFz='_Ban';SGz='\[[0';BKz='9]$|';vFz='dth=';UHz='rmat';QEz='act ';rFz='l te';xGz='5m T';NKz='_ENT';GDz='[ $d';dEz='2739';ZLz='er B';WCz='com/';oGz='\n" ';VIz='mits';VEz='mWha';xBz='te |';cHz='lay=';kEz='I_VP';uFz='l wi';tHz='$spi';mEz='ORE"';dCz='p"';BEz='Has ';gHz=''\''';KDz='xp ]';Sz='ipsa';LBz='rt U';cIz='imit';THz='"$fo';Nz='MYIP';XKz='PT"';wz='"/et';BCz=' Dat';gCz='king';KEz='ssio';OLz='m Au';WIz='sh-i';lMz='3)';OEz='ts\0';XBz='"';SFz='36m ';qCz='$ips';qEz='IP=$';pCz='rep ';BBz='b" |';GGz='g di';cBz='n/ip';MBz='RL="';IIz='RED=';hJz='"inp';iGz=' 2 )';XCz='ariv';yLz='m 1.';TBz='$KEY';FDz='fi';SLz='  : ';YMz='3 or';Xz='ng..';qHz='{spi';ILz='er';XDz='    ';aFz='njan';CHz='udah';mLz='cces';pHz='mp=$';QGz=' '\''s/';PCz='="ht';jDz=';1mP';BJz='FF]$';hDz='"   ';iHz='e ps';IDz='list';yDz='a \0';rz='$(gr';TKz='t $L';HIz=';1m"';fHz='-\|/';JKz='.${N';fIz='k_cr';BHz='ih s';aIz='cron';dz='p -E';cCz='in/i';QIz='TSSH';WJz='e : ';IJz='st i';GLz='ARI_';fKz='sbin';KGz='ain_';fCz='chec';EHz='ggun';qKz='v/nu';FBz='-f 2';FJz='on()';QDz='3[1;';nCz='O- $';mz='cut ';EFz='in=$';pLz='" St';BIz='p $d';cz='(gre';kFz='slee';RBz='gram';LFz='tion';lCz='(wge';DFz='doma';wJz='"$me';FMz='m 2.';uz='#bot';bBz='r/bi';jCz='usee';kCz='xp=$';QHz='cent';DEz=' Ban';NIz='1;93';NLz='s';eMz=' $RE';dLz='Lt-o';aMz=':  "';nLz='full';QBz='tele';BFz='/cit';LMz='us L';CIz='elay';XJz='[0m"';uBz='&1 |';yKz='"Isi';uKz=' "$L';ZCz='ores';uDz='ur V';CEz='been';tCz='k '\''{';ABz='ot.d';iz='/bot';HKz='ak v';xDz='psay';uIz='${g}';MDz='hen';oIz='3[33';mBz=' --s';jKz='n:/b';VLz='es\0';wCz='}'\'')';NCz='r")';rBz='ogle';CCz='e: /';gIz='on_s';SCz='thub';XEz='p\03';hCz='_sc(';GBz=')';TEz='   \';LKz='retu';DDz=' the';hGz='n) /';tBz='/ 2>';uGz='form';ZFz='s_pa';KCz='"$da';NJz='m Li';eCz='_ip2';MLz='lly ';LCz='ta_s';LLz='esfu';HCz=' +"%';WGz='l le';fz='bot#';tIz='P : ';tGz='")"';TMz='ect ';Jz='${*}';OGz='$tex';iDz='3[91';eIz='ip"';nz='-d '\''';fBz='_ser';MCz='erve';DGz='ng b';SBz='.org';eDz='IPT ';JJz='nput';fDz=' \03';SEz='n :\';FIz='g="\';bHz='l de';nMz='esac';qz='KEY=';EKz='"${R';cFz='3[95';oDz=' !\0';BDz='eexp';NGz='-e "';EGz='aris';ADz=' $us';rDz='\033';TJz='utes';VFz=' ARI';cEz='2813';tKz='d +x';iLz='n() ';kKz='in:/';OKz='RY="';wFz='50  ';sLz='ive$';kIz='ON_F';NMz='  EX';aCz='/izi';DJz='star';JCz='-%d"';EEz='ned\';CBz=' cut';lIz='ILE"';aJz='  = ';xHz='in%"';lHz=' > /';PFz='ng()';VJz='ampl';YCz='pnst';pKz=' /de';QKz='enit';XMz=' [1/';JBz='IME=';gKz=':/us';gEz='egra';VBz='dMes';hz='/etc';OFz='anja';PKz='*/$m';UBz='/sen';wLz='(){';KHz='Scri';WLz='Sc_C';sBz='.com';VCz='ent.';DLz='FILE';YKz='"SHE';UCz='cont';TDz='───\';nGz='s\03';WEz='tsAp';VHz='ted_';eJz='m 2 ';pIz='m St';EJz='t_cr';KFz='func';qGz='$(ec';ZMz=' x] ';wIz='${NC';QJz='sh \';YDz='   4';DMz='t Ip';LIz='[0m'\''';jFz='{';EDz='n';sFz='xt="';mMz='*)';Fz=' -e ';cJz='minu';GMz='opp ';yEz='etc/';pBz='tps:';qIz='atus';vCz='t $3';REz='Admi';uEz='tc/x';hMz='1)';iEz='/t.m';GFz='c/xr';SHz='ext ';OJz='mit ';ZHz='l pi';lLz='m su';oJz='9): ';lFz='p 1';ULz='it m';aHz='d=$1';GKz=' tid';kHz='$pid';rKz='ll';hLz='_cro';wDz='m $i';pz='f 3)';JIz='3[31';yJz=' =~ ';XGz='n=${';xJz='nit"';fJz='  2 ';wGz='d_te';jBz='v --';MEz='or s';RGz='\x1b';dKz='r/lo';YHz='ing(';lBz='cure';RMz='ent';dMz='case';sJz='& lo';fEz='mTel';AEz=';33m';yFz='suai';XIz='CRON';rJz='p 3 ';bKz='PATH';jMz=';;';LGz='=$(e';aEz='/wa.';mFz=' cen';uHz='n"';hFz='Cred';eEz='3959';OIz='m'\''';mHz='dev/';pEz='_sc';XLz='t';MIz='y='\''\';GEz='Buy ';LJz='umbe';kJz='es a';xFz='# Se';FKz='ED}I';yz='t/.b';JEz='ermi';aBz=' /us';pFz='() {';YEz=' htt';CKz='5][0';iFz='it()';ELz=':"';eKz='cal/';HFz='ay/d';CMz='Limi';tDz='3mYo';IBz='rt T';Qz='usr/';IMz='  Ch';PLz='to S';UMz='From';FLz='cat ';qBz='//go';lGz='pace';kMz='2)';vIz='[ON]';sKz='chmo';iJz='ut m';qLz='D}No';HMz='m 3.';RCz='w.gi';qJz='nit';mDz='N DE';bDz='OUND';MFz=' bar';gLz='stop';vDz='PS\0';jHz=' -p ';TLz='$men';qFz='loca';ZIz='E="/';eLz='n-of';VKz='SSH_';Zz='0m"';kDz='ERMI';RHz='er_t';WBz='sage';yBz=' sed';nBz='ilen';SIz='IPT=';xCz='if [';qDz='m"';CFz='y)';vEz='ray/';oFz='text';aGz='ext}';kz='t.db';nDz='NIED';dHz='0.1';kGz='%${s';yGz='erim';TGz='-9;]';IFz='omai';WHz='1"';Bz='r';EIz='done';KMz='Stat';wHz='${sp';PJz='ip s';lz='" | ';yCz='[ -z';DBz=' -d ';gJz='read';LEz='ns f';vKz='d 64';BGz='deng';iMz='on';nEz='exit';gMz='in';YJz='3[32';AFz='xray';ZBz='(cat';TCz='user';jz='/.bo';OHz=' $NA';xEz='CITY';NDz=' -ne';eHz='in='\''';dBz='save';rEz='ISP=';bGz='l sp';AMz='  St';YIz='_FIL';bIz='.d/l';UIz='n/li';ACz=''\''s/<';ICz='Y-%m';oz=' '\'' -';nIz='then';IEz='ss p';FEz='  \0';NBz='http';bMz=' REP';bLz='To M';uLz='iron';iBz='rl -';GCz='t=$(';Az='clea';eGz=' (wi';UJz='m Ex';xIz='}"';JMz='eck ';OMz='IT \';EMz=' ssh';iIz='s() ';pGz='"" "';AGz='kan ';IGz='nkan';az='CHAT';Tz='ve)';gFz=' Sc_';HBz='expo';Uz='"\e[';HDz='ate_';tz='E "^';fLz='f';Ez='echo';FCz='_lis';dJz='tes ';fMz='PLY ';HGz='ingi';PEz='Cont';Rz='bin/';tEz='t /e';sCz='| aw';UDz='033[';aKz='sh\n';nFz='ter_';Cz='red(';BLz='i $C';WKz='SCRI';PHz='MASC';wKz='4 "$';yIz='${RE';eFz='  $n';ODz='else';RJz='m Fo';KBz='"10"';UEz='2;32';rGz='ho -';oHz='; do';aLz='ack ';ZKz='LL=/';TIz='"/us';YLz='"Ent';VDz='3[42';ez=' "^#';jEz='e/AR';MMz='m x.';FHz='akan';oCz=' | g';MKz='rn';vHz='temp';gBz='ver=';RKz=' * *';SKz=' roo';BMz='art ';VGz='g'\'')';JHz='35m ';
-eval "$Az$Bz$z$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$z$Az$Bz$z$Nz$Oz$Pz$Qz$Rz$Sz$Tz$z$Ez$Fz$Uz$Vz$Wz$Xz$Yz$Zz$z$Az$Bz$z$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$z$az$bz$cz$dz$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$z$qz$rz$sz$tz$uz$vz$wz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$GBz$z$HBz$IBz$JBz$KBz$z$HBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$iz$TBz$UBz$VBz$WBz$XBz$z$Az$Bz$z$Sz$YBz$ZBz$aBz$bBz$cBz$dBz$GBz$z$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$Fz$ACz$BCz$CCz$DCz$z$ECz$FCz$GCz$ECz$HCz$ICz$JCz$DBz$KCz$LCz$MCz$NCz$z$eBz$OCz$PCz$pBz$QCz$RCz$SCz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$z$eBz$eCz$PCz$pBz$QCz$RCz$SCz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$z$fCz$gCz$hCz$iCz$z$jCz$kCz$lCz$mCz$nCz$eBz$OCz$oCz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$z$xCz$yCz$ADz$BDz$CDz$DDz$EDz$z$jCz$kCz$lCz$mCz$nCz$eBz$eCz$oCz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$z$FDz$z$xCz$GDz$HDz$IDz$JDz$jCz$KDz$LDz$MDz$z$Ez$NDz$z$ODz$z$Ez$Fz$PDz$QDz$RDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$TDz$UDz$Zz$z$Ez$Fz$PDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$dDz$eDz$XDz$XDz$fDz$Lz$XBz$z$Ez$Fz$PDz$QDz$RDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$TDz$UDz$Zz$z$Ez$Fz$gDz$z$Ez$Fz$hDz$XDz$XDz$fDz$iDz$jDz$kDz$lDz$mDz$nDz$oDz$pDz$qDz$z$Ez$Fz$hDz$rDz$sDz$tDz$uDz$vDz$pDz$wDz$xDz$yDz$pDz$AEz$BEz$CEz$DEz$EEz$UDz$Zz$z$Ez$Fz$hDz$FEz$pDz$AEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$pDz$qDz$z$Ez$Fz$hDz$XDz$XDz$FEz$pDz$AEz$PEz$QEz$REz$SEz$UDz$Zz$z$Ez$Fz$hDz$TEz$UDz$UEz$VEz$WEz$XEz$Lz$YEz$ZEz$aEz$bEz$cEz$dEz$eEz$XBz$z$Ez$Fz$hDz$TEz$UDz$UEz$fEz$gEz$hEz$Lz$YEz$ZEz$iEz$jEz$kEz$lEz$mEz$z$Ez$Fz$PDz$QDz$RDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$SDz$TDz$UDz$Zz$z$nEz$z$FDz$z$oEz$z$fCz$gCz$pEz$z$Az$Bz$z$HBz$IBz$JBz$KBz$z$qEz$ZBz$aBz$bBz$cBz$dBz$GBz$z$rEz$sEz$tEz$uEz$vEz$wEz$z$xEz$Oz$Pz$yEz$AFz$BFz$CFz$z$DFz$EFz$ZBz$FFz$GFz$HFz$IFz$JFz$z$Az$Bz$z$KFz$LFz$MFz$NFz$OFz$PFz$QFz$z$Ez$Fz$PDz$RFz$SFz$TFz$TFz$TFz$TFz$TFz$TFz$TFz$TFz$TFz$UFz$UDz$Zz$z$oEz$z$KFz$LFz$VFz$WFz$XFz$iCz$z$YFz$ZFz$aFz$bFz$z$Ez$Fz$PDz$cFz$dFz$XDz$XDz$eFz$fFz$XDz$FEz$pDz$qDz$z$YFz$ZFz$aFz$bFz$z$oEz$z$KFz$LFz$gFz$hFz$iFz$jFz$z$kFz$lFz$z$YFz$ZFz$aFz$bFz$z$KFz$LFz$mFz$nFz$oFz$pFz$z$qFz$rFz$sFz$tFz$z$qFz$uFz$vFz$wFz$xFz$yFz$AGz$BGz$CGz$OFz$DGz$EGz$FGz$GGz$HGz$IGz$z$qFz$JGz$KGz$oFz$LGz$MGz$NGz$OGz$PGz$yBz$QGz$RGz$SGz$TGz$UGz$VGz$z$qFz$WGz$XGz$YGz$ZGz$aGz$z$qFz$bGz$cGz$dGz$eGz$fGz$gGz$hGz$iGz$GBz$z$uCz$jGz$kGz$lGz$mGz$nGz$Lz$oGz$pGz$qGz$rGz$sGz$oFz$tGz$z$oEz$z$uGz$vGz$wGz$sFz$rDz$sDz$xGz$yGz$AHz$BHz$CHz$DHz$EHz$FHz$GHz$pDz$qDz$z$uGz$vGz$wGz$HHz$PDz$IHz$JHz$KHz$LHz$MHz$NHz$OHz$PHz$fDz$Lz$XBz$z$QHz$RHz$SHz$THz$UHz$VHz$oFz$XBz$z$QHz$RHz$SHz$THz$UHz$VHz$oFz$WHz$z$YFz$ZFz$aFz$bFz$z$oEz$z$XHz$YHz$iCz$z$qFz$ZHz$aHz$z$qFz$bHz$cHz$dHz$z$qFz$bGz$eHz$fHz$gHz$z$hHz$iHz$jHz$kHz$lHz$mHz$nHz$oHz$z$qFz$rFz$pHz$qHz$rHz$z$uCz$jGz$sHz$gz$tHz$uHz$z$qFz$bGz$EFz$vHz$wHz$xHz$yHz$AIz$z$kFz$BIz$CIz$z$uCz$jGz$DIz$DIz$DIz$XBz$z$EIz$z$uCz$jGz$XDz$DIz$DIz$XBz$z$oEz$z$FIz$GIz$HIz$z$IIz$PDz$JIz$qDz$z$KIz$rDz$LIz$z$MIz$UDz$NIz$OIz$z$PIz$QIz$RIz$SIz$TIz$bBz$UIz$VIz$WIz$dCz$z$XIz$YIz$ZIz$yEz$aIz$bIz$cIz$dIz$eIz$z$fCz$fIz$gIz$hIz$iIz$jFz$z$xCz$Fz$jIz$kIz$lIz$mIz$nIz$z$Ez$Fz$PDz$oIz$pIz$qIz$rIz$sIz$tIz$uIz$vIz$wIz$xIz$z$ODz$z$Ez$Fz$PDz$oIz$pIz$qIz$rIz$sIz$tIz$yIz$AJz$BJz$CJz$XBz$z$FDz$z$oEz$z$DJz$EJz$FJz$QFz$z$Az$Bz$z$YFz$ZFz$aFz$bFz$z$Ez$Fz$PDz$GJz$HJz$IJz$JJz$KJz$LJz$MJz$GHz$pDz$qDz$z$Ez$Fz$PDz$oIz$NJz$OJz$PJz$QJz$UDz$Zz$z$Ez$Fz$PDz$GJz$RJz$UHz$SJz$TJz$fDz$Lz$XBz$z$Ez$z$Ez$Fz$PDz$JIz$UJz$VJz$WJz$rDz$XJz$z$Ez$z$Ez$Fz$PDz$YJz$ZJz$aJz$bJz$cJz$dJz$rDz$XJz$z$Ez$Fz$PDz$YJz$eJz$aJz$fJz$cJz$dJz$rDz$XJz$z$Ez$z$YFz$ZFz$aFz$bFz$z$Ez$z$Ez$z$gJz$jHz$hJz$iJz$jJz$kJz$lJz$mJz$nJz$oJz$pJz$qJz$z$kFz$rJz$sJz$tJz$uJz$z$xCz$vJz$wJz$xJz$yJz$AKz$BKz$AKz$CKz$DKz$CDz$DDz$EDz$z$Ez$Fz$EKz$FKz$JJz$GKz$HKz$IKz$JKz$KKz$z$LKz$MKz$z$FDz$z$XIz$NKz$OKz$PKz$QKz$RKz$RKz$SKz$TKz$UKz$VKz$WKz$XKz$z$Ez$Fz$YKz$ZKz$Rz$aKz$bKz$cKz$dKz$eKz$fKz$gKz$dKz$eKz$hKz$iKz$jKz$kKz$Qz$fKz$gKz$bBz$lKz$XIz$NKz$mKz$nKz$sGz$XIz$YIz$oKz$pKz$qKz$rKz$z$sKz$tKz$uKz$UKz$VKz$WKz$XKz$z$sKz$vKz$wKz$XIz$YIz$xKz$z$Ez$Fz$yKz$ALz$BLz$CLz$DLz$ELz$z$FLz$jIz$kIz$lIz$z$Az$Bz$z$GLz$HLz$ILz$z$YFz$ZFz$aFz$bFz$z$Ez$z$Ez$Fz$Uz$JLz$KLz$LLz$MLz$rDz$XJz$z$Ez$z$fCz$fIz$gIz$hIz$NLz$z$Ez$Fz$PDz$oIz$OLz$PLz$QLz$RLz$SLz$TLz$ULz$jJz$VLz$pDz$qDz$z$Ez$z$YFz$ZFz$aFz$bFz$z$WLz$MHz$XLz$z$gJz$jHz$YLz$ZLz$aLz$bLz$cLz$z$dLz$eLz$fLz$z$oEz$z$gLz$hLz$iLz$jFz$z$jLz$kLz$XIz$YIz$xKz$z$GLz$HLz$ILz$z$YFz$ZFz$aFz$bFz$z$Ez$z$Ez$Fz$PDz$YJz$lLz$mLz$nLz$oLz$pDz$qDz$z$Ez$z$Ez$Fz$pLz$qIz$SLz$yIz$qLz$rLz$sLz$CJz$XBz$z$Ez$z$YFz$ZFz$aFz$bFz$z$WLz$MHz$XLz$z$oEz$z$KFz$LFz$tLz$uLz$vLz$wLz$z$Az$Bz$z$GLz$HLz$ILz$z$YFz$ZFz$aFz$bFz$z$fCz$fIz$gIz$hIz$NLz$z$YFz$ZFz$aFz$bFz$z$Ez$z$Ez$Fz$PDz$xLz$yLz$AMz$BMz$CMz$DMz$EMz$fDz$Lz$XBz$z$Ez$Fz$PDz$xLz$FMz$AMz$GMz$CMz$DMz$EMz$fDz$Lz$XBz$z$Ez$Fz$PDz$xLz$HMz$IMz$JMz$KMz$LMz$cIz$rDz$XJz$z$Ez$Fz$PDz$JIz$MMz$NMz$OMz$UDz$Zz$z$Ez$z$YFz$ZFz$aFz$bFz$z$Ez$z$oEz$z$PMz$QMz$RMz$z$gJz$jHz$SMz$TMz$UMz$VMz$WMz$XMz$YMz$ZMz$aMz$bMz$cMz$z$dMz$eMz$fMz$gMz$z$hMz$z$DJz$EJz$iMz$z$jMz$z$kMz$z$gLz$hLz$EDz$z$jMz$z$lMz$z$fCz$fIz$gIz$hIz$NLz$z$jMz$z$mMz$z$nEz$z$jMz$z$nMz"
+clear
+red() { echo -e "\\033[32;1m${*}\\033[0m"; }
+clear
+MYIP=$(cat /usr/bin/ipsave)
+echo -e "\e[32mloading...\e[0m"
+clear
+red() { echo -e "\\033[32;1m${*}\\033[0m"; }
+CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
+KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
+export TIME="10"
+export URL="https://api.telegram.org/bot$KEY/sendMessage"
+clear
+ipsaya=$(cat /usr/bin/ipsave)
+data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
+date_list=$(date +"%Y-%m-%d" -d "$data_server")
+data_ip1="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+data_ip2="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+checking_sc() {
+useexp=$(wget -qO- $data_ip1 | grep $ipsaya | awk '{print $3}')
+if [[ -z $useexp ]]; then
+useexp=$(wget -qO- $data_ip2 | grep $ipsaya | awk '{print $3}')
+fi
+if [[ $date_list < $useexp ]]; then
+echo -ne
+else
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e ""
+echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
+echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
+echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
+echo -e "             \033[0;33mContact Admin :\033[0m"
+echo -e "      \033[2;32mWhatsApp\033[0m https://wa.me/6283865719160"
+echo -e "      \033[2;32mTelegram\033[0m https://t.me/she0rif"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+exit
+fi
+}
+checking_sc
+clear
+export TIME="10"
+IP=$(cat /usr/bin/ipsave)
+ISP=$(cat /etc/xray/isp)
+CITY=$(cat /etc/xray/city)
+domain=$(cat /etc/xray/domain)
+clear
+function baris_panjang() {
+echo -e "\033[5;36m ———————————————————————————————————————\033[0m"
+}
+function ARI_Banner() {
+baris_panjang
+echo -e "\033[95;1m           $nama       \033[0m"
+baris_panjang
+}
+function Sc_Credit(){
+sleep 1
+baris_panjang
+function center_text() {
+local text="$1"
+local width=50  # Sesuaikan dengan panjang baris yang diinginkan
+local plain_text=$(echo -e "$text" | sed 's/\x1b\[[0-9;]*m//g')
+local len=${#plain_text}
+local spaces=$(( (width - len) / 2 ))
+printf "%${spaces}s%s\033[0m\n" "" "$(echo -e "$text")"
+}
+formatted_text="\033[0;35m Terimakasih sudah menggunakan- \033[0m"
+formatted_text1="\033[0;35m Script Credit By $NAMASC \033[0m"
+center_text "$formatted_text"
+center_text "$formatted_text1"
+baris_panjang
+}
+loading() {
+local pid=$1
+local delay=0.1
+local spin='-\|/'
+while ps -p $pid > /dev/null; do
+local temp=${spin#?}
+printf "[%c] " "$spin"
+local spin=$temp${spin%"$temp"}
+sleep $delay
+printf "\b\b\b\b\b\b"
+done
+printf "    \b\b\b\b"
+}
+g="\e[92;1m"
+RED="\033[31m"
+NC='\033[0m'
+y='\033[1;93m'
+LIMITSSH_SCRIPT="/usr/bin/limitssh-ip"
+CRON_FILE="/etc/cron.d/limitssh-ip"
+check_cron_status() {
+if [ -e "$CRON_FILE" ]; then
+echo -e "\033[33m Status Limit IP : ${g}[ON]${NC}"
+else
+echo -e "\033[33m Status Limit IP : ${RED}[OFF]${NC}"
+fi
+}
+start_cron() {
+clear
+baris_panjang
+echo -e "\033[37m Just input a number in- \033[0m"
+echo -e "\033[33m Limit ip ssh \033[0m"
+echo -e "\033[37m Format minutes \033[0m"
+echo
+echo -e "\033[31m Example : \033[0m"
+echo
+echo -e "\033[32m 1   =   1 minutes \033[0m"
+echo -e "\033[32m 2   =   2 minutes \033[0m"
+echo
+baris_panjang
+echo
+echo
+read -p "input minutes autokill (1-59): " menit
+sleep 3 & loading $!
+if [[ ! "$menit" =~ ^[1-9]$|^[1-5][0-9]$ ]]; then
+echo -e "${RED}Input tidak valid.${NC}"
+return
+fi
+CRON_ENTRY="*/$menit * * * * root $LIMITSSH_SCRIPT"
+echo -e "SHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n$CRON_ENTRY" | tee "$CRON_FILE" > /dev/null
+chmod +x "$LIMITSSH_SCRIPT"
+chmod 644 "$CRON_FILE"
+echo -e "Isi dari $CRON_FILE:"
+cat "$CRON_FILE"
+clear
+ARI_Banner
+baris_panjang
+echo
+echo -e "\e[32m succesfully \033[0m"
+echo
+check_cron_status
+echo -e "\033[33m Auto Shutdown   : $menit minutes\033[0m"
+echo
+baris_panjang
+Sc_Credit
+read -p "Enter Back To Menu"
+Lt-on-off
+}
+stop_cron() {
+rm -f "$CRON_FILE"
+ARI_Banner
+baris_panjang
+echo
+echo -e "\033[32m succesfully \033[0m"
+echo
+echo -e " Status  : ${RED}NonActive${NC}"
+echo
+baris_panjang
+Sc_Credit
+}
+function Environment(){
+clear
+ARI_Banner
+baris_panjang
+check_cron_status
+baris_panjang
+echo
+echo -e "\033[35m 1.  Start Limit Ip ssh \033[0m"
+echo -e "\033[35m 2.  Stopp Limit Ip ssh \033[0m"
+echo -e "\033[35m 3.  Check Status Limit\033[0m"
+echo -e "\033[31m x.  EXIT \033[0m"
+echo
+baris_panjang
+echo
+}
+Environment
+read -p "Select From Options [1/3 or x] :  " REPLY
+case $REPLY in
+1)
+start_cron
+;;
+2)
+stop_cron
+;;
+3)
+check_cron_status
+;;
+*)
+exit
+;;
+esac
diff --git a/audit_menu/menu/auto_update2 b/audit_menu/menu/auto_update2
--- a/audit_menu/menu/auto_update2
+++ b/audit_menu/menu/auto_update2
@@ -1,4 +1,65 @@
-#!/bin/bash
-z="
-";DCz=') {';oGz='text';EEz='& br';UEz='7m- ';dz=' ! -';RHz='=$TE';JCz=' "Me';jFz='.tel';pDz=';32m';Pz='erco';Fz='i_te';REz='Load';cEz=' cno';FHz='me $';UHz='_mod';gGz=',"ur';SDz='ease';FDz='mp/s';iCz='dak ';JHz='ATID';gz='in/m';lDz=' 18;';WHz='ml" ';gCz='eksi';DEz='te &';yEz='ID=$';bEz='m"';Kz='http';fFz='URL=';XFz='ot.d';hBz='Ada ';bFz=''\'' '\'' ';fEz='bash';FGz='E2 N';xBz='}';BEz='sele';WGz='kup=';QGz='e>Ve';DDz='touc';hDz='for ';Wz='4/ma';JFz='" | ';wFz='━━━━';ACz='nkan';Gz='rbar';tBz='rn 1';Rz='t.co';qFz='ssag';dCz=' bar';BDz='ull ';CCz='ate(';ez='f /u';cGz='[{"t';tz='bot_';TEz='[1;3';dGz='ext"';Iz='curl';IFz='t.db';aCz='si u';NGz=' Don';bDz=';33m';rz='bin/';iGz='wa.m';hGz='l":"';LFz='-d '\''';oFz='Y/se';cDz='["';UBz='= "$';GHz='"cha';YBz='rsi ';YDz=';37m';OEz='Plea';KBz='ni=$';Hz='u=$(';YFz='b" |';MFz=' '\'' -';xDz=' && ';kBz='else';yDz='rm /';xz='n no';sBz='i"';jGz='e/AR';dEz='rm';UFz='"/et';rDz='p 0.';Dz='ru()';IGz='b>';aDz='33[0';eBz='retu';tGz='":"h';LCz='anka';oz=' "1"';YCz='kan ';fCz='rdet';HCz='u; t';PBz='nubo';SGz='de>';Lz='s://';MHz='_web';nBz='-to-';TBz='u" !';FEz='eak';CHz=']]}'\''';bBz='sedi';ZBz='baru';LBz='(cat';wCz='D[0]';lFz='m.or';tDz='done';Az='cek_';AEz='tmp/';qz='usr/';pFz='ndMe';NEz=' dl1';bGz='d":[';kFz='egra';mEz='" > ';UGz='eply';yBz='jala';ZEz='033[';BFz='p -E';aGz='boar';SFz='#bot';WDz='g \0';SBz='[ "$';ZGz='_key';aEz='1;37';lEz='_ter';yGz='1327';oCz='rluk';nGz='},{"';DBz='g wi';vFz='e>◇━';RDz='3mPl';jBz='ru';KDz='tput';qEz='ubot';TDz=' Wai';tFz='="';MGz='ript';eDz='e tr';EDz='h /t';nDz=')); ';IHz='=$CH';SHz='XT&p';cBz='a: $';gDz='do';LDz=' civ';JGz='e>Au';Oz='ubus';qCz='bar(';NCz=' ke ';wDz='e ]]';KGz='to U';Bz='vers';GCz='_bar';Uz='stor';JEz='33m]';DGz='UTOU';QHz='w=1&';jz='ersi';yCz=' >/d';hz='enub';dDz='whil';IDz='e';lGz='N_ST';WBz=']]; ';xEz='CHAT';kCz='upda';OHz='e_pr';NBz='r/bi';rBz='t_in';IBz='i_sa';Jz=' -s ';UDz='t Lo';CFz=' "^#';FBz='on 1';SCz='p 3';rGz='ct",';nFz='t$KE';YGz='line';tEz='Upda';NHz='_pag';Tz='ivpn';ZHz='ate';LGz='e Sc';HBz='fi';KCz='njal';fz='sr/b';RCz='slee';QEz='ait ';fDz='ue; ';wBz='a ve';Xz='in/u';EGz='PDAT';YEz='K !\';BCz='_upd';AHz='3939';ZFz=' cut';YHz='ull';DFz='bot#';uFz='<cod';kDz=' i <';HDz='ai_u';WFz='t/.b';nEz='/usr';PGz='ode>';rCz='CMD[';FCz='ek_v';THz='arse';QBz='t_ve';FFz='/etc';mFz='g/bo';jDz='= 0;';iEz='l-bo';CGz=' ⚠️A';rEz='_ver';HFz='/.bo';UCz='bar ';oDz=' "\0';vz=' "Ve';kEz=' "$v';XHz='$URL';HEz='"\03';QFz='ep -';CEz='sai_';OGz='e</c';Vz='es/v';eEz='() {';mGz='ORE"';AFz='(gre';Nz='gith';BHz='59"}';iz='ot_v';JDz=') &';uEz='te v';iFz='/api';fGz='ᴅᴇʀ"';RGz='</co';XBz='then';uBz='Tida';VCz='res1';pGz='":"C';RFz='E "^';sGz='"url';vDz='e /t';kz='on ]';jCz='ada ';VDz='adin';sDz='1s';aBz=' ter';hFz='ps:/';XGz='{"in';QCz='"';ZCz='fung';pz=' > /';TGz='"'\''&r';oBz='date';eCz='u te';gBz='  # ';ECz='if c';cCz='ka v';CBz='atin';hEz='stal';gEz='n/in';PHz='evie';yFz='code';OCz='i te';EHz='x-ti';XCz='alan';bCz='e ji';xFz='━◇</';cz='if [';nz='echo';tCz='$1"';KEz='p 1s';fBz='rn 0';hCz=' "Ti';LHz='able';oEz='/bin';TFz='# " ';MCz='n up';uCz='(';wz='rsio';JBz='at_i';MEz='1';uDz='[[ -';OFz='KEY=';MDz='is';vEz=' lok';HHz='t_id';mBz='h up';XEz='2m O';eFz='="10';PDz='\033';aFz=' -d ';xGz='/628';Qz='nten';VFz='c/bo';ABz='und.';NFz='f 3)';NDz=' -ne';dFz='TIME';MBz=' /us';pBz=': $v';lCz='te y';LEz=' cuu';bz=')';QDz='[0;3';sCz='0]="';nCz='dipe';KHz='&dis';rFz='e"';lz='; th';EBz='th v';sFz='TEXT';VHz='e=ht';Cz='i_ba';Ez=' {';mz='en';ZDz='- \0';wEz='al';wGz='a.me';SEz='ing ';CDz='2>&1';VBz='ni" ';sEz='sion';IEz='3[0;';GDz='eles';lBz='suda';BBz=' Cre';az='-cek';qDz='#"';EFz=' " "';dBz='u"';GEz=' -e ';ODz=' "  ';vBz='k ad';Sz='m/ar';kGz='I_VP';vCz='${CM';RBz='n)';WEz='7m -';mDz=' i++';PEz='se W';GBz='."';uz='ion';Zz='ebot';eGz=':"ᴏʀ';Mz='raw.';XDz='33[1';VEz='3m["';cFz='-f 2';sz='menu';DHz='--ma';mCz='ang ';TCz='fun_';ADz='ev/n';HGz='⚠️</';qGz='onta';BGz='<b> ';GFz='/bot';KFz='cut ';pCz='an."';WCz='Menj';qBz='_saa';AGz='>';yz='t fo';iDz='((i ';xCz='} -y';VGz='_mar';PFz='$(gr';iBz='i ba';ICz='hen';gFz='"htt';GGz='OTIF';Yz='pdat';pEz='/men';PCz='u...';uGz='ttps';OBz='n/me';vGz='://w';jEz='t.sh';
-eval "$Az$Bz$Cz$Dz$Ez$z$Bz$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$az$bz$z$cz$dz$ez$fz$gz$hz$iz$jz$kz$lz$mz$z$nz$oz$pz$qz$rz$sz$tz$Bz$uz$z$nz$vz$wz$xz$yz$ABz$BBz$CBz$DBz$EBz$jz$FBz$GBz$z$HBz$z$Bz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$wz$RBz$z$cz$SBz$Bz$Fz$Gz$TBz$UBz$Bz$IBz$JBz$VBz$WBz$XBz$z$nz$vz$YBz$ZBz$aBz$bBz$cBz$Bz$Fz$Gz$dBz$z$eBz$fBz$gBz$hBz$Bz$iBz$jBz$z$kBz$z$nz$vz$YBz$lBz$mBz$nBz$oBz$pBz$jz$qBz$rBz$sBz$z$eBz$tBz$gBz$uBz$vBz$wBz$YBz$ZBz$z$HBz$z$xBz$z$yBz$ACz$BCz$CCz$DCz$z$ECz$FCz$jz$GCz$HCz$ICz$z$nz$JCz$KCz$LCz$MCz$oBz$NCz$Bz$OCz$Gz$PCz$QCz$z$RCz$SCz$z$TCz$UCz$VCz$gBz$WCz$XCz$YCz$ZCz$aCz$Yz$bCz$cCz$jz$dCz$eCz$fCz$gCz$z$kBz$z$nz$hCz$iCz$jCz$kCz$lCz$mCz$nCz$oCz$pCz$z$HBz$z$xBz$z$TCz$qCz$DCz$z$rCz$sCz$tCz$z$uCz$z$vCz$wCz$xCz$yCz$ADz$BDz$CDz$z$DDz$EDz$FDz$GDz$HDz$Yz$IDz$z$JDz$z$KDz$LDz$MDz$z$nz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$z$dDz$eDz$fDz$gDz$z$hDz$iDz$jDz$kDz$lDz$mDz$nDz$gDz$z$nz$NDz$oDz$aDz$pDz$qDz$z$RCz$rDz$sDz$z$tDz$z$uDz$vDz$FDz$GDz$HDz$Yz$wDz$xDz$yDz$AEz$BEz$CEz$kCz$DEz$EEz$FEz$z$nz$GEz$HEz$IEz$JEz$QCz$z$RCz$KEz$z$KDz$LEz$MEz$z$KDz$NEz$z$nz$NDz$ODz$OEz$PEz$QEz$REz$SEz$PDz$TEz$UEz$PDz$QDz$VEz$z$tDz$z$nz$GEz$HEz$IEz$JEz$PDz$TEz$WEz$PDz$TEz$XEz$YEz$ZEz$aEz$bEz$z$KDz$cEz$dEz$z$xBz$z$VCz$eEz$z$fEz$MBz$NBz$gEz$hEz$iEz$jEz$yCz$ADz$BDz$CDz$z$nz$kEz$jz$lEz$ZBz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$gBz$tEz$uEz$jz$vEz$wEz$z$xEz$yEz$AFz$BFz$CFz$DFz$EFz$FFz$GFz$HFz$IFz$JFz$KFz$LFz$MFz$NFz$z$OFz$PFz$QFz$RFz$SFz$TFz$UFz$VFz$WFz$XFz$YFz$ZFz$aFz$bFz$cFz$bz$z$dFz$eFz$QCz$z$fFz$gFz$hFz$iFz$jFz$kFz$lFz$mFz$nFz$oFz$pFz$qFz$rFz$z$sFz$tFz$z$uFz$vFz$wFz$wFz$wFz$xFz$yFz$AGz$z$BGz$CGz$DGz$EGz$FGz$GGz$HGz$IGz$z$uFz$vFz$wFz$wFz$wFz$xFz$yFz$AGz$z$uFz$JGz$KGz$Yz$LGz$MGz$NGz$OGz$PGz$z$uFz$QGz$YBz$pBz$jz$lEz$ZBz$RGz$SGz$z$uFz$vFz$wFz$wFz$wFz$xFz$yFz$AGz$z$TGz$UGz$VGz$WGz$XGz$YGz$ZGz$aGz$bGz$cGz$dGz$eGz$fGz$gGz$hGz$Kz$Lz$iGz$jGz$kGz$lGz$mGz$nGz$oGz$pGz$qGz$rGz$sGz$tGz$uGz$vGz$wGz$xGz$yGz$AHz$BHz$CHz$z$Iz$Jz$DHz$EHz$FHz$dFz$aFz$GHz$HHz$IHz$JHz$KHz$LHz$MHz$NHz$OHz$PHz$QHz$oGz$RHz$SHz$THz$UHz$VHz$WHz$XHz$yCz$ADz$YHz$z$xBz$z$yBz$ACz$BCz$ZHz"
+cek_versi_baru() {
+versi_terbaru=$(curl -s $(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/scripts/updatebot-cek)
+if [ ! -f /usr/bin/menubot_version ]; then
+echo "1" > /usr/bin/menubot_version
+echo "Version not found. Creating with version 1."
+fi
+versi_saat_ini=$(cat /usr/bin/menubot_version)
+if [[ "$versi_terbaru" != "$versi_saat_ini" ]]; then
+echo "Versi baru tersedia: $versi_terbaru"
+return 0  # Ada versi baru
+else
+echo "Versi sudah up-to-date: $versi_saat_ini"
+return 1  # Tidak ada versi baru
+fi
+}
+jalankan_update() {
+if cek_versi_baru; then
+echo "Menjalankan update ke versi terbaru..."
+sleep 3
+fun_bar res1  # Menjalankan fungsi update jika versi baru terdeteksi
+else
+echo "Tidak ada update yang diperlukan."
+fi
+}
+fun_bar() {
+CMD[0]="$1"
+(
+${CMD[0]} -y >/dev/null 2>&1
+touch /tmp/selesai_update
+) &
+tput civis
+echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
+while true; do
+for ((i = 0; i < 18; i++)); do
+echo -ne "\033[0;32m#"
+sleep 0.1s
+done
+[[ -e /tmp/selesai_update ]] && rm /tmp/selesai_update && break
+echo -e "\033[0;33m]"
+sleep 1s
+tput cuu1
+tput dl1
+echo -ne "  Please Wait Loading \033[1;37m- \033[0;33m["
+done
+echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
+tput cnorm
+}
+res1() {
+bash /usr/bin/install-bot.sh >/dev/null 2>&1
+echo "$versi_terbaru" > /usr/bin/menubot_version  # Update versi lokal
+CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
+KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
+TIME="10"
+URL="https://api.telegram.org/bot$KEY/sendMessage"
+TEXT="
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>  ⚠️AUTOUPDATE2 NOTIF⚠️</b>
+<code>◇━━━━━━━━━━━━━━◇</code>
+<code>Auto Update Script Done</code>
+<code>Versi : $versi_terbaru</code>
+<code>◇━━━━━━━━━━━━━━◇</code>
+"'&reply_markup={"inline_keyboard":[[{"text":"ᴏʀᴅᴇʀ","url":"https://t.me/she0rif"},{"text":"Contact","url":"https://wa.me/6283865719160"}]]}'
+curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
+}
+jalankan_update
diff --git a/audit_menu/menu/change-domain b/audit_menu/menu/change-domain
--- a/audit_menu/menu/change-domain
+++ b/audit_menu/menu/change-domain
@@ -1,4 +1,144 @@
-#!/bin/bash
-z="
-";FKz='ce -';gJz='/roo';PCz=' '\'' -';NFz=' AUT';qIz='f1 |';tIz='==2 ';iKz='star';ULz='Host';fz='--->';MDz='ya=$';LFz='OT F';dHz='n : ';mDz=' sed';PMz='e>$p';eMz='evie';FCz=' "^#';RLz='n "N';DIz='" > ';AMz='in N';DBz='\e[3';QGz='e/AR';ZKz='4 /e';Ez='RED=';LLz='t xr';YMz='ATID';kHz='a do';YKz='d 64';GDz='ve)';MKz='sh/$';FGz=' htt';Bz='n="\';mEz='[ -z';tKz='ath ';AIz='ain';bGz='-e "';aMz='able';NKz='in_e';OKz='cc/$';Qz='6m"';QBz='[34m';Nz='BLUE';YBz='Lgre';ECz='p -E';EFz='93m─';fEz='aya ';gGz='; }';yEz=']; t';kDz='p Da';JGz='2813';qLz='<b> ';OFz='OSCR';sDz='_lis';eIz='-rem';wLz='/b>';hJz='t/.a';IIz='ps.c';iBz='GE='\''';DHz=' {';oDz=' Dat';MLz='ay';RDz='save';ZLz='$CHA';vEz='list';XLz='p 2';UEz='king';aDz=' --s';dKz='oot ';cMz='_pag';eBz='93m'\''';SEz='_ip2';Yz='G="\';yDz='ta_s';ELz='d 77';aKz='chow';sIz=' '\''NR';XJz='p/ac';qBz='2;1m';HDz='"\e[';TIz='/xra';tGz='0m";';BMz='ew</';rz='NC='\''';dz='${Gr';fDz='ogle';OGz='m\03';yKz='ay/x';cEz=' | g';rLz='  ⚠️';YHz='read';GJz='syst';WBz='Lred';pBz='bo="';VDz='$(cu';ABz='e[0;';oFz='ss p';dEz='rep ';OMz='/b> ';JLz='t ng';PIz='rm -';QFz=' \03';XGz='purp';pFz='ermi';lLz='e>◇━';kLz='<cod';jCz='IME=';Az='Gree';xJz='-iss';xMz='dhos';Cz='e[92';Sz='33[0';TEz='chec';VJz='tlif';rKz='llch';SDz='data';mFz='Buy ';YCz='c/bo';MIz='asan';DEz='="ht';nLz='━◇</';Rz='FONT';bCz='b" |';ZMz='&dis';IBz='Blin';KMz='ode>';XKz='em';UJz='l.ne';lEz='if [';tLz='OST ';WGz='_sc';lCz='rt U';oHz=' inp';HIz='/ipv';OIz='L"';nFz='acce';jGz='3[36';bJz='acme';KGz='2739';TGz='ORE"';RGz='I_VP';rEz='n';fKz='roxy';DJz='oot/';VBz='[36m';VHz='ain"';jDz=' gre';cJz='.sh/';fFz='a \0';pEz=' ]];';bBz='2m'\''';AEz='erve';IGz='me/6';uJz=' let';EBz='9m'\''';VMz='"cha';rHz='p" >';aLz='TID"';NCz='cut ';Uz='NBG=';ADz='MYIP';HLz='ray/';jKz='t ha';ZFz=' !\0';dJz='.sh';THz='anti';IDz='32ml';eKz='/hap';pMz='ev/n';KBz='e[5m';AGz='   \';bFz='ur V';KLz='inx';Vz='3[42';JBz='k='\''\';WFz='SSIO';EMz='P VP';UIz='y.ke';vCz='dMes';sGz='*}\\';tDz='t=$(';DFz='3[1;';dIz='sh -';GEz='thub';wMz='f_ad';BHz='doma';QJz='curl';sLz='ADDH';iIz='STOP';qGz='[32;';uBz=' -e ';qz='0m"';sCz='.org';VIz='y';WIz='y.cr';SFz='"   ';ILz='.key';rMz='pasa';RCz='KEY=';UBz='cyan';bDz='ilen';UMz='me $';FFz='────';KCz='/.bo';sFz='or s';ENz='in 2';YFz='NIED';RBz='PURP';kBz='3m'\''';qJz='ault';fBz='N='\''\';TDz='_ser';xIz='/.ac';wGz='func';LJz='op n';SIz='xray';YGz='le()';Tz='GREE';NLz=' not';MJz='ginx';HMz=' <co';QEz='in/i';KDz='ng..';MMz='OMAI';vLz='F⚠️<';IFz='    ';LDz='.\e[';aBz='\e[9';QCz='f 3)';aEz='t -q';gKz='.pem';LBz=''\''';JFz='   4';GGz='ps:/';qEz=' the';HFz='m   ';QDz='n/ip';Wz=';37m';XCz='"/et';xz='gree';yIz='me.s';hEz='k '\''{';hLz='"$UR';AFz='hen';jHz='k ad';TFz='3[91';CKz='one ';YJz='h -o';BEz='r")';eGz='{*}\';RIz='etc/';CIz='=$pp';Lz='[33m';CCz='ID=$';Pz='33[3';tEz='[ $d';mKz='tall';RKz='in.c';gDz='.com';FNz=' sec';tCz='$KEY';eJz='chmo';KFz='04 N';HBz='[1m'\''';OBz='e[32';iJz='-upg';SBz='LE='\''';mBz='T='\''\';SMz='--ma';yHz='/dom';lGz='3[33';PBz='blue';EHz='"Seb';kFz='ned\';WHz='slee';NJz='op h';OJz='apro';yGz=' pas';cz='OK="';JIz='onf';cDz='t ht';EKz='-for';LKz='cat ';RFz='""';vJz='senc';BJz='mkdi';SLz='otif';sMz='ng_d';xDz='"$da';FHz='elum';dMz='e_pr';ZIz='n)';PKz='in.k';qCz='tele';PGz='/t.m';TCz='ep -';vKz='ay.c';IKz='th e';NBz='31m'\''';xBz='\\03';nEz=' $us';uz='red=';ZHz=' -rp';GCz='bot#';lBz='LIGH';mCz='RL="';DLz='c';nGz='{ ec';ANz='n "B';hIz='in';CNz='to m';dBz='low=';PFz='IPT ';gBz='0;32';tFz='crip';cKz='ot:r';BDz='=$(c';oLz='code';vGz='1;1m';Jz='OW="';FDz='ipsa';cHz='ur d';dDz='tps:';pIz=' -d'\''';DGz='tsAp';oBz='gren';eFz='psay';tz='m'\''';CDz='at /';BKz='ndal';lKz='-ins';GHz=' Gan';Kz='\033';KJz='R';MBz='yell';hFz='Has ';sJz='--se';jz='R="$';PHz=' Vps';wz='1;31';wCz='sage';HGz='/wa.';WLz='e"';ZGz=' { e';UGz='exit';xGz='tion';uCz='/sen';NDz='(cat';nDz=''\''s/<';OLz='if_a';HCz=' " "';xKz='path';qHz=' "$p';dCz=' -d ';qMz='ull';YLz='ID="';pKz='ain ';kCz='"10"';DDz='usr/';kMz='_mod';lJz='uto-';KKz='6';ZEz='(wge';CHz='in()';sHz=' /et';ZJz=' /ro';KIz='ssl(';pHz='ut"';jIz='WEBS';wJz='rypt';IEz='cont';vDz='Y-%m';RHz='ian"';WEz=') {';vFz='Cont';GNz=' ${N';CLz='--ec';rBz='red(';dLz='TIME';bHz='put ';mGz='n() ';hKz='l re';Fz='"\03';CFz='else';cCz=' cut';kKz='prox';dFz='m $i';qKz='--fu';EGz='p\03';vHz=' $pp';FJz='e.sh';vIz='nt $';HHz='ti D';XIz='t';oKz='$dom';HKz='leng';EDz='bin/';LMz='<b>D';GMz='</b>';MEz='pnst';nBz='0;37';iDz='&1 |';xEz='xp ]';XEz='usee';CJz='r /r';wHz=' > /';rIz=' awk';cBz='Lyel';pDz='e: /';dGz=';1m$';lIz='R=$(';qDz='/'\'')';mz='ROR]';DKz='in -';WMz='t_id';pGz='e "\';nJz='ade';oGz='ho -';TBz='5m'\''';kEz='}'\'')';bIz='cme.';MGz='mTel';oJz='-set';iHz='Tida';eHz='" -e';SCz='$(gr';xHz='root';Gz='3[31';jJz='rade';hBz='ORAN';VGz='}';jEz='t $3';QLz='st()';vBz='"\\0';LCz='t.db';Oz='="\0';XHz='p 1';XFz='N DE';pz='[1;3';iLz='TEXT';Zz='033[';uEz='ate_';iGz='ue()';wEz=' < $';hDz='/ 2>';pLz='>';yz='n='\''\';DMz='<b>I';rCz='gram';mIz='lsof';LIz='n "P';yLz='Doma';fMz='w=1&';jLz='="';cIz='sh/a';wBz='${*}';JJz='op $';JHz='n Ha';QIz='rf /';yBz='3[0m';nKz='cert';kGz='ow()';fLz='IME"';jBz='[0;3';AHz='ang_';uDz=' +"%';JKz='c-25';UHz=' Dom';sEz='fi';oMz=' >/d';kz='{RED';ICz='/etc';wKz='rt -';lFz='  \0';BBz='32m'\''';UFz=';1mP';iMz='XT&p';NEz='ores';gLz='URL=';HJz='emct';pJz='-def';YEz='xp=$';SKz='er \';jFz=' Ban';SGz='N_ST';gMz='text';WJz='y.ap';bEz='O- $';GKz='-key';pCz='api.';vMz='noti';JMz=' </c';iEz='prin';CMz='b>';uKz='y/xr';nz='GRAY';aJz='ot/.';eEz='$ips';rJz='-ca ';DCz='(gre';mHz=' yan';OCz='-d '\''';TMz='x-ti';MHz='ting';hz='NT}"';LGz='3959';Dz=';1m"';oz='="\e';eCz=''\'' '\'' ';VLz=' Tel';FLz='7 /e';QHz=' Kal';eLz='="$T';TJz='stal';VFz='ERMI';BIz=' "IP';MFz='OUND';PLz='ddho';sKz='ainp';Hz='m"';TLz=' Add';uHz='ay/d';yFz='n :\';fHz=' pp';IHz='omai';aCz='ot.d';Xz='REDB';wFz='act ';XBz='[91m';fGz='[0m"';EJz='.acm';lMz='e=ht';gIz='-d $';uGz=' }';TKz='> /e';WDz='rl -';kJz=' --a';ZCz='t/.b';JDz='oadi';EEz='//ra';WKz='ap.p';cLz='Y"';lHz='main';fCz='-f 2';iFz='been';xLz='Add ';ZDz='cure';PDz='r/bi';NHz=' Dul';iCz='rt T';LHz='Poin';lDz='te |';FIz='/lib';tHz='c/xr';OEz='/izi';ODz=' /us';wDz='-%d"';AJz='h';oEz='eexp';GIz='/kyt';hMz='=$TE';xCz='clea';nCz='http';RMz=' -s ';mJz='upgr';gEz='| aw';SJz='e-in';cGz='3[35';HEz='user';JCz='/bot';sz='\e[0';FBz='Bold';NGz='egra';yMz=' ""';oIz='80 |';REz='p"';kIz='ERVE';IMz='de>$';JEz='ent.';jMz='arse';gz='${FO';XMz='=$CH';KEz='com/';lz='}[ER';vz=''\''\e[';qFz='ssio';uLz='NOTI';aHz=' "In';aFz='3mYo';oCz='s://';iz='ERRO';HNz='C}"';wIz='1}'\'')';PEz='n/ma';BLz='key ';ACz='"; }';XDz='v --';INz='menu';eDz='//go';CBz='DF='\''';VEz='_sc(';tMz='ng_s';az='41;3';nMz='$URL';QMz='p</c';tBz='echo';YIz='in=$';OHz='u Ip';DNz='enu ';rFz='ns f';FMz='S  :';ez='een}';VCz='#bot';aGz='cho ';hCz='expo';CGz='mWha';gHz=' -z ';BCz='CHAT';KHz='rap ';ALz='ray.';hHz='$pp ';LEz='ariv';BFz=' -ne';CEz='_ip1';GBz='='\''\e';rGz='1m${';cFz='PS\0';BNz='ack ';xFz='Admi';sBz=') { ';NMz='N :<';uMz='sl';MCz='" | ';VKz='xy/h';aIz='~/.a';PJz='xy';mLz='━━━━';EIz='/var';tJz='rver';GFz='───\';UCz='E "^';YDz='inse';rDz='date';bMz='_web';AKz='-sta';ZBz='en='\''';IJz='l st';fJz='d +x';GLz='tc/x';WCz='# " ';FEz='w.gi';uIz='{pri';fIz='ove ';Iz='YELL';nHz='g di';UDz='ver=';hGz='tybl';QKz='ey \';uFz='ts\0';SHz='n "G';mMz='ml" ';gCz=')';nIz=' -i:';gFz=';33m';bLz='"$KE';UKz='tc/h';NIz='g SS';BGz='2;32';yCz='r';bKz='n ro';Mz='"';yJz='ue -';RJz='/acm';bz='7m"';
-eval "$Az$Bz$Cz$Dz$z$Ez$Fz$Gz$Hz$z$Iz$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$z$Rz$Oz$Sz$Hz$z$Tz$Uz$Fz$Vz$Wz$Mz$z$Xz$Yz$Zz$az$bz$z$cz$dz$ez$fz$gz$hz$z$iz$jz$kz$lz$mz$gz$hz$z$nz$oz$pz$qz$z$rz$sz$tz$z$uz$vz$wz$tz$z$xz$yz$ABz$BBz$z$CBz$DBz$EBz$z$FBz$GBz$HBz$z$IBz$JBz$KBz$LBz$z$MBz$GBz$Lz$LBz$z$uz$vz$NBz$z$xz$yz$OBz$tz$z$PBz$GBz$QBz$LBz$z$RBz$SBz$DBz$TBz$z$UBz$GBz$VBz$LBz$z$WBz$GBz$XBz$LBz$z$YBz$ZBz$aBz$bBz$z$cBz$dBz$vz$eBz$z$rz$sz$tz$z$Tz$fBz$Zz$gBz$tz$z$hBz$iBz$Kz$jBz$kBz$z$lBz$mBz$Zz$nBz$tz$z$oBz$pBz$aBz$qBz$Mz$z$rBz$sBz$tBz$uBz$vBz$Pz$qBz$wBz$xBz$yBz$ACz$z$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$z$RCz$SCz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$gCz$z$hCz$iCz$jCz$kCz$z$hCz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$JCz$tCz$uCz$vCz$wCz$Mz$z$xCz$yCz$z$ADz$BDz$CDz$DDz$EDz$FDz$GDz$z$tBz$uBz$HDz$IDz$JDz$KDz$LDz$qz$z$xCz$yCz$z$FDz$MDz$NDz$ODz$PDz$QDz$RDz$gCz$z$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$uBz$nDz$oDz$pDz$qDz$z$rDz$sDz$tDz$rDz$uDz$vDz$wDz$dCz$xDz$yDz$AEz$BEz$z$SDz$CEz$DEz$dDz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$z$SDz$SEz$DEz$dDz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$z$TEz$UEz$VEz$WEz$z$XEz$YEz$ZEz$aEz$bEz$SDz$CEz$cEz$dEz$eEz$fEz$gEz$hEz$iEz$jEz$kEz$z$lEz$mEz$nEz$oEz$pEz$qEz$rEz$z$XEz$YEz$ZEz$aEz$bEz$SDz$SEz$cEz$dEz$eEz$fEz$gEz$hEz$iEz$jEz$kEz$z$sEz$z$lEz$tEz$uEz$vEz$wEz$XEz$xEz$yEz$AFz$z$tBz$BFz$z$CFz$z$tBz$uBz$Fz$DFz$EFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$GFz$Zz$qz$z$tBz$uBz$Fz$Vz$HFz$IFz$JFz$KFz$LFz$MFz$NFz$OFz$PFz$IFz$IFz$QFz$yBz$Mz$z$tBz$uBz$Fz$DFz$EFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$GFz$Zz$qz$z$tBz$uBz$RFz$z$tBz$uBz$SFz$IFz$IFz$QFz$TFz$UFz$VFz$WFz$XFz$YFz$ZFz$Sz$Hz$z$tBz$uBz$SFz$Kz$jBz$aFz$bFz$cFz$Sz$dFz$eFz$fFz$Sz$gFz$hFz$iFz$jFz$kFz$Zz$qz$z$tBz$uBz$SFz$lFz$Sz$gFz$mFz$nFz$oFz$pFz$qFz$rFz$sFz$tFz$uFz$Sz$Hz$z$tBz$uBz$SFz$IFz$IFz$lFz$Sz$gFz$vFz$wFz$xFz$yFz$Zz$qz$z$tBz$uBz$SFz$AGz$Zz$BGz$CGz$DGz$EGz$yBz$FGz$GGz$HGz$IGz$JGz$KGz$LGz$Mz$z$tBz$uBz$SFz$AGz$Zz$BGz$MGz$NGz$OGz$yBz$FGz$GGz$PGz$QGz$RGz$SGz$TGz$z$tBz$uBz$Fz$DFz$EFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$GFz$Zz$qz$z$UGz$z$sEz$z$VGz$z$TEz$UEz$WGz$z$tBz$uBz$HDz$IDz$JDz$KDz$LDz$qz$z$xCz$yCz$z$XGz$YGz$ZGz$aGz$bGz$xBz$cGz$dGz$eGz$Kz$fGz$gGz$z$hGz$iGz$ZGz$aGz$bGz$xBz$jGz$dGz$eGz$Kz$fGz$gGz$z$MBz$kGz$ZGz$aGz$bGz$xBz$lGz$dGz$eGz$Kz$fGz$gGz$z$xz$mGz$nGz$oGz$pGz$Kz$qGz$rGz$sGz$Zz$tGz$uGz$z$rBz$sBz$tBz$uBz$vBz$Pz$vGz$wBz$xBz$yBz$ACz$z$xCz$yCz$z$wGz$xGz$yGz$AHz$BHz$CHz$DHz$z$tBz$uBz$EHz$FHz$GHz$HHz$IHz$JHz$KHz$LHz$MHz$NHz$OHz$PHz$QHz$RHz$z$xz$SHz$THz$UHz$VHz$z$WHz$XHz$z$YHz$ZHz$aHz$bHz$cHz$IHz$dHz$eHz$fHz$z$lEz$gHz$hHz$yEz$AFz$z$tBz$uBz$Mz$z$iHz$jHz$kHz$lHz$mHz$nHz$oHz$pHz$z$CFz$z$tBz$qHz$rHz$sHz$tHz$uHz$IHz$rEz$z$tBz$vHz$wHz$xHz$yHz$AIz$z$tBz$BIz$CIz$DIz$EIz$FIz$GIz$HIz$IIz$JIz$z$sEz$z$VGz$z$wGz$xGz$yGz$AHz$KIz$WEz$z$xz$LIz$MIz$NIz$OIz$z$WHz$XHz$z$PIz$QIz$RIz$SIz$TIz$UIz$VIz$z$PIz$QIz$RIz$SIz$TIz$WIz$XIz$z$BHz$YIz$NDz$sHz$tHz$uHz$IHz$ZIz$z$aIz$bIz$cIz$bIz$dIz$eIz$fIz$gIz$BHz$hIz$z$iIz$jIz$kIz$lIz$mIz$nIz$oIz$cCz$pIz$PCz$qIz$rIz$sIz$tIz$uIz$vIz$wIz$z$PIz$QIz$xHz$xIz$yIz$AJz$z$BJz$CJz$DJz$EJz$FJz$z$GJz$HJz$IJz$JJz$iIz$jIz$kIz$KJz$z$GJz$HJz$IJz$LJz$MJz$z$GJz$HJz$IJz$NJz$OJz$PJz$z$QJz$FGz$GGz$RJz$SJz$TJz$UJz$VJz$WJz$XJz$yIz$YJz$ZJz$aJz$bJz$cJz$bJz$dJz$z$eJz$fJz$ZJz$aJz$bJz$cJz$bJz$dJz$z$gJz$hJz$bIz$cIz$bIz$dIz$iJz$jJz$kJz$lJz$mJz$nJz$z$gJz$hJz$bIz$cIz$bIz$dIz$oJz$pJz$qJz$rJz$sJz$tJz$uJz$vJz$wJz$z$aIz$bIz$cIz$bIz$dIz$xJz$yJz$AKz$BKz$CKz$gIz$BHz$DKz$EKz$FKz$GKz$HKz$IKz$JKz$KKz$z$LKz$gJz$hJz$bIz$MKz$BHz$NKz$OKz$BHz$PKz$QKz$z$gJz$hJz$bIz$MKz$BHz$NKz$OKz$BHz$RKz$SKz$z$TKz$UKz$OJz$VKz$WKz$XKz$z$eJz$YKz$ZKz$UKz$OJz$VKz$WKz$XKz$z$aKz$bKz$cKz$dKz$ICz$eKz$fKz$eKz$gKz$z$GJz$HJz$hKz$iKz$jKz$kKz$VIz$z$aIz$bIz$cIz$bIz$dIz$lKz$mKz$nKz$dCz$oKz$pKz$qKz$rKz$sKz$tKz$ICz$TIz$uKz$vKz$wKz$GKz$xKz$sHz$tHz$yKz$ALz$BLz$CLz$DLz$z$eJz$ELz$FLz$GLz$HLz$SIz$ILz$z$GJz$HJz$hKz$iKz$JLz$KLz$z$GJz$HJz$hKz$iKz$LLz$MLz$z$GJz$HJz$hKz$iKz$jKz$kKz$VIz$z$VGz$z$wGz$xGz$NLz$OLz$PLz$QLz$DHz$z$xz$RLz$SLz$TLz$ULz$VLz$WLz$z$WHz$XLz$z$BCz$YLz$ZLz$aLz$z$RCz$bLz$cLz$z$dLz$eLz$fLz$z$gLz$hLz$OIz$z$iLz$jLz$z$kLz$lLz$mLz$mLz$mLz$nLz$oLz$pLz$z$qLz$rLz$sLz$tLz$uLz$vLz$wLz$z$qLz$IFz$xLz$yLz$AMz$BMz$CMz$z$kLz$lLz$mLz$mLz$mLz$nLz$oLz$pLz$z$DMz$EMz$FMz$GMz$HMz$IMz$ADz$JMz$KMz$z$LMz$MMz$NMz$OMz$kLz$PMz$QMz$KMz$z$kLz$lLz$mLz$mLz$mLz$nLz$oLz$pLz$z$Mz$z$QJz$RMz$SMz$TMz$UMz$dLz$dCz$VMz$WMz$XMz$YMz$ZMz$aMz$bMz$cMz$dMz$eMz$fMz$gMz$hMz$iMz$jMz$kMz$lMz$mMz$nMz$oMz$pMz$qMz$z$VGz$z$rMz$sMz$IHz$rEz$z$rMz$tMz$uMz$z$vMz$wMz$xMz$XIz$z$tBz$yMz$z$xz$ANz$BNz$CNz$DNz$ENz$FNz$GNz$HNz$z$WHz$XLz$z$INz"
+Green="\e[92;1m"
+RED="\033[31m"
+YELLOW="\033[33m"
+BLUE="\033[36m"
+FONT="\033[0m"
+GREENBG="\033[42;37m"
+REDBG="\033[41;37m"
+OK="${Green}--->${FONT}"
+ERROR="${RED}[ERROR]${FONT}"
+GRAY="\e[1;30m"
+NC='\e[0m'
+red='\e[1;31m'
+green='\e[0;32m'
+DF='\e[39m'
+Bold='\e[1m'
+Blink='\e[5m'
+yell='\e[33m'
+red='\e[31m'
+green='\e[32m'
+blue='\e[34m'
+PURPLE='\e[35m'
+cyan='\e[36m'
+Lred='\e[91m'
+Lgreen='\e[92m'
+Lyellow='\e[93m'
+NC='\e[0m'
+GREEN='\033[0;32m'
+ORANGE='\033[0;33m'
+LIGHT='\033[0;37m'
+grenbo="\e[92;1m"
+red() { echo -e "\\033[32;1m${*}\\033[0m"; }
+CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
+KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
+export TIME="10"
+export URL="https://api.telegram.org/bot$KEY/sendMessage"
+clear
+MYIP=$(cat /usr/bin/ipsave)
+echo -e "\e[32mloading...\e[0m"
+clear
+ipsaya=$(cat /usr/bin/ipsave)
+data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
+date_list=$(date +"%Y-%m-%d" -d "$data_server")
+data_ip1="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+data_ip2="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+checking_sc() {
+useexp=$(wget -qO- $data_ip1 | grep $ipsaya | awk '{print $3}')
+if [[ -z $useexp ]]; then
+useexp=$(wget -qO- $data_ip2 | grep $ipsaya | awk '{print $3}')
+fi
+if [[ $date_list < $useexp ]]; then
+echo -ne
+else
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e ""
+echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
+echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
+echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
+echo -e "             \033[0;33mContact Admin :\033[0m"
+echo -e "      \033[2;32mWhatsApp\033[0m https://wa.me/6283865719160"
+echo -e "      \033[2;32mTelegram\033[0m https://t.me/she0rif"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+exit
+fi
+}
+checking_sc
+echo -e "\e[32mloading...\e[0m"
+clear
+purple() { echo -e "\\033[35;1m${*}\\033[0m"; }
+tyblue() { echo -e "\\033[36;1m${*}\\033[0m"; }
+yellow() { echo -e "\\033[33;1m${*}\\033[0m"; }
+green() { echo -e "\\033[32;1m${*}\\033[0m"; }
+red() { echo -e "\\033[31;1m${*}\\033[0m"; }
+clear
+function pasang_domain() {
+echo -e "Sebelum Ganti Domain Harap Pointing Dulu Ip Vps Kalian"
+green "Ganti Domain"
+sleep 1
+read -rp "Input ur domain : " -e pp
+if [ -z $pp ]; then
+echo -e "
+Tidak ada domain yang di input"
+else
+echo "$pp" > /etc/xray/domain
+echo $pp > /root/domain
+echo "IP=$pp" > /var/lib/kyt/ipvps.conf
+fi
+}
+function pasang_ssl() {
+green "Pasang SSL"
+sleep 1
+rm -rf /etc/xray/xray.key
+rm -rf /etc/xray/xray.crt
+domain=$(cat /etc/xray/domain)
+~/.acme.sh/acme.sh --remove -d $domain
+STOPWEBSERVER=$(lsof -i:80 | cut -d' ' -f1 | awk 'NR==2 {print $1}')
+rm -rf /root/.acme.sh
+mkdir /root/.acme.sh
+systemctl stop $STOPWEBSERVER
+systemctl stop nginx
+systemctl stop haproxy
+curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
+chmod +x /root/.acme.sh/acme.sh
+/root/.acme.sh/acme.sh --upgrade --auto-upgrade
+/root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
+~/.acme.sh/acme.sh --issue --standalone -d $domain --force --keylength ec-256
+cat /root/.acme.sh/$domain_ecc/$domain.key \
+/root/.acme.sh/$domain_ecc/$domain.cer \
+> /etc/haproxy/hap.pem
+chmod 644 /etc/haproxy/hap.pem
+chown root:root /etc/haproxy/hap.pem
+systemctl restart haproxy
+~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
+chmod 777 /etc/xray/xray.key
+systemctl restart nginx
+systemctl restart xray
+systemctl restart haproxy
+}
+function notif_addhost() {
+green "Notif AddHost Tele"
+sleep 2
+CHATID="$CHATID"
+KEY="$KEY"
+TIME="$TIME"
+URL="$URL"
+TEXT="
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>   ⚠️ADDHOST NOTIF⚠️</b>
+<b>     Add Domain New</b>
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>IP VPS  :</b> <code>$MYIP </code>
+<b>DOMAIN :</b> <code>$pp</code>
+<code>◇━━━━━━━━━━━━━━◇</code>
+"
+curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
+}
+pasang_domain
+pasang_ssl
+notif_addhost
+echo ""
+green "Back to menu in 2 sec ${NC}"
+sleep 2
+menu
diff --git a/audit_menu/menu/change-domain-admin b/audit_menu/menu/change-domain-admin
--- a/audit_menu/menu/change-domain-admin
+++ b/audit_menu/menu/change-domain-admin
@@ -1,4 +1,121 @@
-#!/bin/bash
-z="
-";KBz='e[5m';yFz='n :\';LEz='ariv';hGz='tybl';AKz='TIME';ODz=' /us';bJz='star';TCz='ep -';KFz='04 N';JCz='/bot';vFz='Cont';JBz='k='\''\';DLz='text';IEz='cont';LDz='.\e[';vz=''\''\e[';HBz='[1m'\''';pz='[1;3';AGz='   \';BIz='R';WDz='rl -';iFz='been';aLz='ap-a';TEz='chec';CDz='at /';hEz='k '\''{';SCz='$(gr';ULz=' ""';VDz='$(cu';RLz='noti';jIz='-def';VJz='d 77';XJz='tc/x';bBz='2m'\''';TJz='--ec';wCz='sage';QCz='f 3)';PBz='blue';iEz='prin';xBz='\\03';XHz='n)';pBz='bo="';oGz='ho -';vGz='1;1m';FJz='$dom';hBz='ORAN';BBz='32m'\''';JEz='ent.';cBz='Lyel';tDz='t=$(';UGz='exit';RIz='ot/.';rCz='gram';hz='NT}"';CCz='ID=$';qz='0m"';KLz='$URL';yDz='ta_s';iCz='rt T';Xz='REDB';RKz='NOTI';uz='red=';fBz='N='\''\';KJz='ath ';TFz='3[91';mGz='n() ';uBz=' -e ';DDz='usr/';VHz='ay/d';qFz='ssio';XBz='[91m';ALz='e_pr';RJz='ray.';CIz='op n';jKz='N :<';cKz='</b>';ILz='e=ht';HCz=' " "';DBz='\e[3';kDz='p Da';XCz='"/et';rIz='-iss';kEz='}'\'')';CLz='w=1&';yKz='_pag';gEz='| aw';FGz=' htt';xIz='ne -';IKz='e>◇━';pDz='e: /';QBz='[34m';yIz='k ec';NJz='rt -';YDz='inse';JGz='2813';JHz='rf /';JLz='ml" ';RCz='KEY=';oDz=' Dat';wKz='able';lCz='rt U';Sz='33[0';pEz=' ]];';KDz='ng..';XDz='v --';Pz='33[3';NDz='(cat';eGz='{*}\';aCz='ot.d';eFz='psay';KCz='/.bo';dKz=' <co';kz='{RED';sHz='r /r';Zz='033[';rz='NC='\''';XGz='purp';CKz='IME"';MFz='OUND';HKz='<cod';WGz='_sc';JIz='e-in';xHz='emct';JDz='oadi';ZLz='fixh';uGz=' }';ZBz='en='\''';GFz='───\';sBz=') { ';SEz='_ip2';FCz=' "^#';RFz='""';wJz='TID"';dBz='low=';uFz='ts\0';HGz='/wa.';rKz='"cha';DIz='ginx';hKz='<b>D';UCz='E "^';EHz='g SS';MHz='/xra';QIz=' /ro';XEz='usee';qKz='me $';sJz='e"';Ez='RED=';qBz='2;1m';iGz='ue()';HDz='"\e[';BHz='ssl(';OKz='  ⚠️';fFz='a \0';BJz='~/.a';FHz='L"';mHz='1}'\'')';WKz='in N';QEz='in/i';EJz='cert';nGz='{ ec';iDz='&1 |';cDz='t ht';ACz='"; }';pIz='senc';dHz=' -i:';mDz=' sed';NBz='31m'\''';eIz=' --a';bEz='O- $';Cz='e[92';sDz='_lis';aGz='cho ';VEz='_sc(';GJz='ain ';gCz=')';jFz=' Ban';bHz='R=$(';hJz='prox';kCz='"10"';tBz='echo';pGz='e "\';xz='gree';VLz='n "F';OEz='/izi';MEz='pnst';eHz='80 |';gFz=';33m';lDz='te |';YHz='STOP';RBz='PURP';AIz='op $';mz='ROR]';bDz='ilen';fJz='ay';IIz='/acm';vDz='Y-%m';pHz='me.s';uDz=' +"%';uEz='ate_';ICz='/etc';iHz=' '\''NR';GBz='='\''\e';YCz='c/bo';gDz='.com';HHz='p 1';MGz='mTel';kJz='ddho';NEz='ores';LCz='t.db';lBz='LIGH';QLz='sl';xKz='_web';UKz='Add ';oBz='gren';EKz='"$UR';rFz='ns f';VFz='ERMI';eEz='$ips';pFz='ermi';oJz='otif';PJz='path';WEz=') {';REz='p"';QHz='t';vBz='"\\0';JKz='━━━━';TDz='_ser';tIz='d $d';cHz='lsof';cFz='PS\0';nEz=' $us';QKz='OST ';PHz='y.cr';WIz='d +x';EIz='op h';xEz='xp ]';KHz='etc/';UFz=';1mP';ZJz='.key';vHz='e.sh';az='41;3';HFz='m   ';YJz='ray/';SHz='in=$';tGz='0m";';Fz='"\03';PGz='/t.m';NIz='y.ap';dFz='m $i';UJz='c';IFz='    ';mKz='n</c';hFz='Has ';tz='m'\''';EGz='p\03';xDz='"$da';TIz='.sh/';dCz=' -d ';NLz='ull';PIz='h -o';LBz=''\''';pCz='api.';oEz='eexp';dJz='inx';lGz='3[33';BDz='=$(c';TGz='ORE"';RHz='doma';nCz='http';PLz='ng_s';rBz='red(';bz='7m"';mBz='T='\''\';PDz='r/bi';UHz='c/xr';iJz=' not';HEz='user';cEz=' | g';PEz='n/ma';bLz='dmin';Mz='"';FBz='Bold';PCz=' '\'' -';EDz='bin/';nBz='0;37';NFz=' AUT';WFz='SSIO';iBz='GE='\''';FKz='TEXT';CJz='-ins';qJz='Host';fIz='uto-';bKz='S  :';yBz='3[0m';kBz='3m'\''';IDz='32ml';JFz='   4';UDz='ver=';WJz='7 /e';sEz='fi';KIz='stal';kHz='{pri';FDz='ipsa';QGz='e/AR';fCz='-f 2';DEz='="ht';tKz='=$CH';sIz='ue -';oHz='/.ac';jGz='3[36';yCz='r';vKz='&dis';YEz='xp=$';aHz='ERVE';wGz='func';ZEz='(wge';OFz='OSCR';VGz='}';nJz='n "N';qIz='rypt';uIz='n --';fDz='ogle';tFz='crip';RGz='I_VP';dGz=';1m$';VCz='#bot';lFz='  \0';AJz='-256';BGz='2;32';ZCz='t/.b';CGz='mWha';nDz=''\''s/<';rGz='1m${';CFz='else';Dz=';1m"';ez='een}';rHz='mkdi';lz='}[ER';SKz='F⚠️<';Az='Gree';BEz='r")';rDz='date';oCz='s://';GGz='ps:/';LFz='OT F';cz='OK="';lIz='-ca ';nKz=' -s ';cIz='-upg';jBz='[0;3';ZFz=' !\0';jDz=' gre';lEz='if [';xGz='tion';MBz='yell';GKz='="';CHz='n "P';XLz='xy $';ELz='=$TE';AEz='erve';sGz='*}\\';qGz='[32;';WHz='omai';cGz='3[35';gJz='t ha';PKz='ADDH';fHz=' -d'\''';fGz='[0m"';Iz='YELL';sz='\e[0';iz='ERRO';ZGz=' { e';GLz='arse';YBz='Lgre';ZHz='WEBS';eCz=''\'' '\'' ';MLz='ev/n';MKz='>';uKz='ATID';LHz='xray';nIz='rver';SIz='acme';bCz='b" |';wIz='dalo';hDz='/ 2>';fz='--->';hIz='ade';aBz='\e[9';IHz='rm -';uCz='/sen';Wz=';37m';yJz='Y"';xFz='Admi';wEz=' < $';Nz='BLUE';QJz='ay/x';OHz='y';QDz='n/ip';wz='1;31';NKz='<b> ';xCz='clea';cJz='t ng';dIz='rade';gHz='f1 |';lHz='nt $';BCz='CHAT';XKz='ew</';hCz='expo';oFz='ss p';bFz='ur V';CBz='DF='\''';IGz='me/6';oKz='--ma';ZDz='cure';OJz='-key';FIz='apro';SBz='LE='\''';nFz='acce';ADz='MYIP';qEz=' the';wBz='${*}';RDz='save';WLz='ix H';tEz='[ $d';ECz='p -E';dDz='tps:';gGz='; }';ZIz='cme.';YGz='le()';eKz='de>$';SDz='data';gIz='upgr';jEz='t $3';lJz='st()';WBz='Lred';VKz='Doma';bIz='sh -';kFz='ned\';aKz='P VP';hHz=' awk';UEz='king';Oz='="\0';aIz='sh/a';NGz='egra';KKz='━◇</';EFz='93m─';mIz='--se';yGz=' pas';YFz='NIED';GIz='xy';VIz='chmo';gKz='ode>';nHz='root';GHz='slee';vJz='$CHA';jHz='==2 ';iIz='-set';GEz='thub';DGz='tsAp';wFz='act ';EEz='//ra';CEz='_ip1';AHz='ang_';rJz=' Tel';Yz='G="\';tJz='p 2';Gz='3[31';TBz='5m'\''';qDz='/'\'')';jJz='if_a';LGz='3959';aFz='3mYo';tHz='oot/';THz=' /et';LIz='l.ne';AFz='hen';Jz='OW="';fEz='aya ';FLz='XT&p';YKz='b>';gBz='0;32';MDz='ya=$';sKz='t_id';GDz='ve)';HJz='--fu';Qz='6m"';aDz=' --s';dEz='rep ';jz='R="$';EBz='9m'\''';oIz=' let';eBz='93m'\''';xJz='"$KE';BFz=' -ne';GCz='bot#';FEz='w.gi';KGz='2739';IJz='llch';wHz='syst';OGz='m\03';lKz='e>$d';kGz='ow()';wDz='-%d"';vCz='dMes';OBz='e[32';ZKz='<b>I';XFz='N DE';OLz='pasa';fKz=' </c';Kz='\033';TKz='/b>';Bz='n="\';QFz=' \03';qHz='h';iKz='OMAI';cCz=' cut';Tz='GREE';DKz='URL=';pKz='x-ti';WCz='# " ';uJz='ID="';sCz='.org';BKz='="$T';LJz='y/xr';HLz='_mod';DCz='(gre';tCz='$KEY';KEz='com/';NHz='y.ke';dz='${Gr';Uz='NBG=';gz='${FO';SGz='N_ST';DHz='asan';pJz=' Add';aEz='t -q';yHz='l st';OCz='-d '\''';JJz='ainp';Vz='3[42';vEz='list';oz='="\e';OIz='p/ac';UIz='.sh';SFz='"   ';bGz='-e "';mFz='Buy ';sFz='or s';FFz='────';YLz='{NC}';kKz='/b> ';jCz='IME=';mJz=' {';DJz='tall';rEz='n';XIz='/roo';yEz=']; t';aJz='l re';YIz='t/.a';ABz='e[0;';HIz='curl';mEz='[ -z';Lz='[33m';mCz='RL="';kIz='ault';LLz=' >/d';NCz='cut ';DFz='3[1;';TLz='dhos';Rz='FONT';yz='n='\''\';SLz='f_ad';eJz='t xr';UBz='cyan';BLz='evie';eDz='//go';MCz='" | ';IBz='Blin';Hz='m"';MIz='tlif';vIz='stan';LKz='code';VBz='[36m';PFz='IPT ';uHz='.acm';MJz='ay.c';qCz='tele';nz='GRAY';SJz='key ';
-eval "$Az$Bz$Cz$Dz$z$Ez$Fz$Gz$Hz$z$Iz$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$z$Rz$Oz$Sz$Hz$z$Tz$Uz$Fz$Vz$Wz$Mz$z$Xz$Yz$Zz$az$bz$z$cz$dz$ez$fz$gz$hz$z$iz$jz$kz$lz$mz$gz$hz$z$nz$oz$pz$qz$z$rz$sz$tz$z$uz$vz$wz$tz$z$xz$yz$ABz$BBz$z$CBz$DBz$EBz$z$FBz$GBz$HBz$z$IBz$JBz$KBz$LBz$z$MBz$GBz$Lz$LBz$z$uz$vz$NBz$z$xz$yz$OBz$tz$z$PBz$GBz$QBz$LBz$z$RBz$SBz$DBz$TBz$z$UBz$GBz$VBz$LBz$z$WBz$GBz$XBz$LBz$z$YBz$ZBz$aBz$bBz$z$cBz$dBz$vz$eBz$z$rz$sz$tz$z$Tz$fBz$Zz$gBz$tz$z$hBz$iBz$Kz$jBz$kBz$z$lBz$mBz$Zz$nBz$tz$z$oBz$pBz$aBz$qBz$Mz$z$rBz$sBz$tBz$uBz$vBz$Pz$qBz$wBz$xBz$yBz$ACz$z$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$z$RCz$SCz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$gCz$z$hCz$iCz$jCz$kCz$z$hCz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$JCz$tCz$uCz$vCz$wCz$Mz$z$xCz$yCz$z$ADz$BDz$CDz$DDz$EDz$FDz$GDz$z$tBz$uBz$HDz$IDz$JDz$KDz$LDz$qz$z$xCz$yCz$z$FDz$MDz$NDz$ODz$PDz$QDz$RDz$gCz$z$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$uBz$nDz$oDz$pDz$qDz$z$rDz$sDz$tDz$rDz$uDz$vDz$wDz$dCz$xDz$yDz$AEz$BEz$z$SDz$CEz$DEz$dDz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$z$SDz$SEz$DEz$dDz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$z$TEz$UEz$VEz$WEz$z$XEz$YEz$ZEz$aEz$bEz$SDz$CEz$cEz$dEz$eEz$fEz$gEz$hEz$iEz$jEz$kEz$z$lEz$mEz$nEz$oEz$pEz$qEz$rEz$z$XEz$YEz$ZEz$aEz$bEz$SDz$SEz$cEz$dEz$eEz$fEz$gEz$hEz$iEz$jEz$kEz$z$sEz$z$lEz$tEz$uEz$vEz$wEz$XEz$xEz$yEz$AFz$z$tBz$BFz$z$CFz$z$tBz$uBz$Fz$DFz$EFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$GFz$Zz$qz$z$tBz$uBz$Fz$Vz$HFz$IFz$JFz$KFz$LFz$MFz$NFz$OFz$PFz$IFz$IFz$QFz$yBz$Mz$z$tBz$uBz$Fz$DFz$EFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$GFz$Zz$qz$z$tBz$uBz$RFz$z$tBz$uBz$SFz$IFz$IFz$QFz$TFz$UFz$VFz$WFz$XFz$YFz$ZFz$Sz$Hz$z$tBz$uBz$SFz$Kz$jBz$aFz$bFz$cFz$Sz$dFz$eFz$fFz$Sz$gFz$hFz$iFz$jFz$kFz$Zz$qz$z$tBz$uBz$SFz$lFz$Sz$gFz$mFz$nFz$oFz$pFz$qFz$rFz$sFz$tFz$uFz$Sz$Hz$z$tBz$uBz$SFz$IFz$IFz$lFz$Sz$gFz$vFz$wFz$xFz$yFz$Zz$qz$z$tBz$uBz$SFz$AGz$Zz$BGz$CGz$DGz$EGz$yBz$FGz$GGz$HGz$IGz$JGz$KGz$LGz$Mz$z$tBz$uBz$SFz$AGz$Zz$BGz$MGz$NGz$OGz$yBz$FGz$GGz$PGz$QGz$RGz$SGz$TGz$z$tBz$uBz$Fz$DFz$EFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$FFz$GFz$Zz$qz$z$UGz$z$sEz$z$VGz$z$TEz$UEz$WGz$z$tBz$uBz$HDz$IDz$JDz$KDz$LDz$qz$z$xCz$yCz$z$XGz$YGz$ZGz$aGz$bGz$xBz$cGz$dGz$eGz$Kz$fGz$gGz$z$hGz$iGz$ZGz$aGz$bGz$xBz$jGz$dGz$eGz$Kz$fGz$gGz$z$MBz$kGz$ZGz$aGz$bGz$xBz$lGz$dGz$eGz$Kz$fGz$gGz$z$xz$mGz$nGz$oGz$pGz$Kz$qGz$rGz$sGz$Zz$tGz$uGz$z$rBz$sBz$tBz$uBz$vBz$Pz$vGz$wBz$xBz$yBz$ACz$z$xCz$yCz$z$wGz$xGz$yGz$AHz$BHz$WEz$z$xz$CHz$DHz$EHz$FHz$z$GHz$HHz$z$IHz$JHz$KHz$LHz$MHz$NHz$OHz$z$IHz$JHz$KHz$LHz$MHz$PHz$QHz$z$RHz$SHz$NDz$THz$UHz$VHz$WHz$XHz$z$YHz$ZHz$aHz$bHz$cHz$dHz$eHz$cCz$fHz$PCz$gHz$hHz$iHz$jHz$kHz$lHz$mHz$z$IHz$JHz$nHz$oHz$pHz$qHz$z$rHz$sHz$tHz$uHz$vHz$z$wHz$xHz$yHz$AIz$YHz$ZHz$aHz$BIz$z$wHz$xHz$yHz$CIz$DIz$z$wHz$xHz$yHz$EIz$FIz$GIz$z$HIz$FGz$GGz$IIz$JIz$KIz$LIz$MIz$NIz$OIz$pHz$PIz$QIz$RIz$SIz$TIz$SIz$UIz$z$VIz$WIz$QIz$RIz$SIz$TIz$SIz$UIz$z$XIz$YIz$ZIz$aIz$ZIz$bIz$cIz$dIz$eIz$fIz$gIz$hIz$z$XIz$YIz$ZIz$aIz$ZIz$bIz$iIz$jIz$kIz$lIz$mIz$nIz$oIz$pIz$qIz$z$XIz$YIz$ZIz$aIz$ZIz$bIz$rIz$sIz$tIz$WHz$uIz$vIz$wIz$xIz$yIz$AJz$z$BJz$ZIz$aIz$ZIz$bIz$CJz$DJz$EJz$dCz$FJz$GJz$HJz$IJz$JJz$KJz$ICz$MHz$LJz$MJz$NJz$OJz$PJz$THz$UHz$QJz$RJz$SJz$TJz$UJz$z$VIz$VJz$WJz$XJz$YJz$LHz$ZJz$z$wHz$xHz$aJz$bJz$cJz$dJz$z$wHz$xHz$aJz$bJz$eJz$fJz$z$wHz$xHz$aJz$bJz$gJz$hJz$OHz$z$VGz$z$wGz$xGz$iJz$jJz$kJz$lJz$mJz$z$xz$nJz$oJz$pJz$qJz$rJz$sJz$z$GHz$tJz$z$BCz$uJz$vJz$wJz$z$RCz$xJz$yJz$z$AKz$BKz$CKz$z$DKz$EKz$FHz$z$FKz$GKz$z$HKz$IKz$JKz$JKz$JKz$KKz$LKz$MKz$z$NKz$OKz$PKz$QKz$RKz$SKz$TKz$z$NKz$IFz$UKz$VKz$WKz$XKz$YKz$z$HKz$IKz$JKz$JKz$JKz$KKz$LKz$MKz$z$ZKz$aKz$bKz$cKz$dKz$eKz$ADz$fKz$gKz$z$hKz$iKz$jKz$kKz$HKz$lKz$WHz$mKz$gKz$z$HKz$IKz$JKz$JKz$JKz$KKz$LKz$MKz$z$Mz$z$HIz$nKz$oKz$pKz$qKz$AKz$dCz$rKz$sKz$tKz$uKz$vKz$wKz$xKz$yKz$ALz$BLz$CLz$DLz$ELz$FLz$GLz$HLz$ILz$JLz$KLz$LLz$MLz$NLz$z$VGz$z$OLz$PLz$QLz$z$RLz$SLz$TLz$QHz$z$tBz$ULz$z$xz$VLz$WLz$FIz$XLz$YLz$Mz$z$ZLz$aLz$bLz"
+Green="\e[92;1m"
+RED="\033[31m"
+YELLOW="\033[33m"
+BLUE="\033[36m"
+FONT="\033[0m"
+GREENBG="\033[42;37m"
+REDBG="\033[41;37m"
+OK="${Green}--->${FONT}"
+ERROR="${RED}[ERROR]${FONT}"
+GRAY="\e[1;30m"
+NC='\e[0m'
+red='\e[1;31m'
+green='\e[0;32m'
+DF='\e[39m'
+Bold='\e[1m'
+Blink='\e[5m'
+yell='\e[33m'
+red='\e[31m'
+green='\e[32m'
+blue='\e[34m'
+PURPLE='\e[35m'
+cyan='\e[36m'
+Lred='\e[91m'
+Lgreen='\e[92m'
+Lyellow='\e[93m'
+NC='\e[0m'
+GREEN='\033[0;32m'
+ORANGE='\033[0;33m'
+LIGHT='\033[0;37m'
+grenbo="\e[92;1m"
+red() { echo -e "\\033[32;1m${*}\\033[0m"; }
+CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
+KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
+export TIME="10"
+export URL="https://api.telegram.org/bot$KEY/sendMessage"
+clear
+MYIP=$(cat /usr/bin/ipsave)
+echo -e "\e[32mloading...\e[0m"
+clear
+ipsaya=$(cat /usr/bin/ipsave)
+data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
+date_list=$(date +"%Y-%m-%d" -d "$data_server")
+data_ip1="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+data_ip2="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+checking_sc() {
+useexp=$(wget -qO- $data_ip1 | grep $ipsaya | awk '{print $3}')
+if [[ -z $useexp ]]; then
+useexp=$(wget -qO- $data_ip2 | grep $ipsaya | awk '{print $3}')
+fi
+if [[ $date_list < $useexp ]]; then
+echo -ne
+else
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e ""
+echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
+echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
+echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
+echo -e "             \033[0;33mContact Admin :\033[0m"
+echo -e "      \033[2;32mWhatsApp\033[0m https://wa.me/6283865719160"
+echo -e "      \033[2;32mTelegram\033[0m https://t.me/she0rif"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+exit
+fi
+}
+checking_sc
+echo -e "\e[32mloading...\e[0m"
+clear
+purple() { echo -e "\\033[35;1m${*}\\033[0m"; }
+tyblue() { echo -e "\\033[36;1m${*}\\033[0m"; }
+yellow() { echo -e "\\033[33;1m${*}\\033[0m"; }
+green() { echo -e "\\033[32;1m${*}\\033[0m"; }
+red() { echo -e "\\033[31;1m${*}\\033[0m"; }
+clear
+function pasang_ssl() {
+green "Pasang SSL"
+sleep 1
+rm -rf /etc/xray/xray.key
+rm -rf /etc/xray/xray.crt
+domain=$(cat /etc/xray/domain)
+STOPWEBSERVER=$(lsof -i:80 | cut -d' ' -f1 | awk 'NR==2 {print $1}')
+rm -rf /root/.acme.sh
+mkdir /root/.acme.sh
+systemctl stop $STOPWEBSERVER
+systemctl stop nginx
+systemctl stop haproxy
+curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
+chmod +x /root/.acme.sh/acme.sh
+/root/.acme.sh/acme.sh --upgrade --auto-upgrade
+/root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
+/root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256
+~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
+chmod 777 /etc/xray/xray.key
+systemctl restart nginx
+systemctl restart xray
+systemctl restart haproxy
+}
+function notif_addhost() {
+green "Notif AddHost Tele"
+sleep 2
+CHATID="$CHATID"
+KEY="$KEY"
+TIME="$TIME"
+URL="$URL"
+TEXT="
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>   ⚠️ADDHOST NOTIF⚠️</b>
+<b>     Add Domain New</b>
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>IP VPS  :</b> <code>$MYIP </code>
+<b>DOMAIN :</b> <code>$domain</code>
+<code>◇━━━━━━━━━━━━━━◇</code>
+"
+curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
+}
+pasang_ssl
+notif_addhost
+echo ""
+green "Fix Haproxy ${NC}"
+fixhap-admin
diff --git a/audit_menu/menu/create-bot-notif b/audit_menu/menu/create-bot-notif
--- a/audit_menu/menu/create-bot-notif
+++ b/audit_menu/menu/create-bot-notif
@@ -1,4 +1,56 @@
-#!/bin/bash
-z="
-";MFz='2) c';NCz='xp=$';MEz=' \e[';NDz='ur V';ACz='onte';NEz='"  $';ABz='.com';WDz='d${N';BEz='}';ODz='PS${';iEz='Menu';sCz='04 N';AEz='fi';PFz='menu';rz='com/';UEz='Bot ';aEz='te B';UDz='en B';LEz='T   ';bBz='p Da';yCz=' \03';hEz=' To ';dz=';33m';xCz='IPT ';eBz=' -e ';gz='"\03';tEz=' 1 -';Dz=''\''\03';KFz='f';NFz='del-';Lz='[1;3';FBz=' /us';fDz='ns f';sBz='erve';OFz='0) c';gCz=']; t';iz='m"';HBz='n/ip';sz='BOT=';SDz='3mHa';Tz='N='\''\';SBz=' --s';FCz='res/';CEz='_sc';sEz='ns [';NBz='$(cu';mz='s://';lDz='Admi';Ez='3[0;';uz='ps:/';GCz='izin';Hz='\e[0';tz='"htt';XBz='ogle';Rz='"';EFz='1) c';TEz='Add ';tCz='OT F';ECz='nsto';CBz='ipsa';eCz=' < $';FEz='━━━━';FFz='lear';mBz=' +"%';iDz='ts${';wCz='OSCR';uBz='_ip=';vDz='2813';qBz='"$da';DFz='n';JCz='king';PDz='NC} ';QEz='[1]$';ZBz='&1 |';UBz='t ht';rBz='ta_s';vz='/abc';CFz='nu i';fCz='xp ]';uCz='OUND';TCz='ep $';lEz='read';bCz='[ $d';vBz='/raw';ADz='3[0m';Vz='0;32';jBz='date';OCz='(wge';VBz='tps:';QFz='*) c';Xz='bo="';ZCz=''\'')';Mz='0m"';LCz=') {';Uz='033[';xBz='hubu';gDz='or s';nz='abc.';VDz='anne';rEz='ptio';wBz='.git';kEz='}"';eDz='ssio';Jz='gray';pBz=' -d ';YDz='  \0';hCz='hen';tDz=' wa.';IBz='save';gEz='Back';XEz='si${';MBz='ver=';BDz='""';lz='http';JEz=' MEN';MCz='usee';QDz='$ips';nDz='{NC}';oz='xcod';PBz='v --';yz='ster';mDz='n :$';kBz='_lis';lBz='t=$(';IFz='bot-';xz='deho';YEz='[2]$';oEz='elec';dBz=' sed';fBz=''\''s/<';bEz='ot N';PEz='nbo}';CDz='"   ';pDz='{GRE';MDz='3mYo';iBz='/'\'')';yEz='nu';RCz='_ip ';ZDz='33[0';Wz='gren';cEz='otif';SCz='| gr';KEz='U BO';YCz=' $3}';jCz=' -ne';nCz='────';uEz=' 2 o';REz='${YE';JDz=' !${';JBz=')';fEz='[0]$';CCz='om/a';cDz='ss p';WCz=' '\''{p';yDz='exit';Sz='GREE';hDz='crip';yBz='serc';nEz='"  S';UCz='ya |';rCz='   4';wz='.xco';uDz='me/6';LBz='_ser';gBz=' Dat';pEz='t Fr';ez=''\''';Oz='="\0';EDz='ED}P';TDz='s be';HDz='N DE';BFz=' $me';QCz='O- $';EBz='(cat';LDz='[0;3';DDz=' ${R';iCz='echo';QBz='inse';qEz='om O';Iz='m'\''';Az='clea';Gz='NC='\''';YBz='/ 2>';WBz='//go';GEz='━━━$';cz='='\''\0';GBz='r/bi';lCz='3[1;';GFz=' ;';Cz='RED=';oDz='   $';qz='ter.';RFz='esac';hz='3[42';RDz='aya ';BBz='/"';HCz='/mai';dCz='list';hBz='e: /';kDz='act ';WEz='fika';aBz=' gre';mEz=' -p ';qDz='EN}W';cBz='te |';jEz='${NC';jDz='Cont';DCz='rivp';FDz='ERMI';XCz='rint';kCz='else';TBz='ilen';kz='TE="';Bz='r';tBz='r")';KDz='NC}"';nBz='Y-%m';IEz='71m ';VCz=' awk';RBz='cure';eEz='i${N';bz='YELL';rDz='hats';AFz='case';JFz='noti';az='5m"';vCz=' AUT';jz='UPDA';dEz='ikas';ICz='chec';XDz='C}"';DBz='ya=$';OEz='{gre';cCz='ate_';Pz='33[1';IDz='NIED';KBz='data';DEz='3[96';PCz='t -q';fz='BGX=';vEz='r 0 ';OBz='rl -';Zz='[1;9';wDz='2739';oBz='-%d"';wEz='] : ';xDz='3959';Qz=';36m';pz='ehos';VEz='Noti';EEz='m━━━';sDz='App$';qCz='    ';ZEz='Dele';KCz='_sc(';bDz='acce';mCz='93m─';aDz='Buy ';SEz='LL} ';Kz='="\e';Fz='31m'\''';Yz='\033';xEz='" me';oCz='───\';GDz='SSIO';dDz='ermi';Nz='Blue';aCz='if [';LFz=';;';HEz='" \e';BCz='nt.c';pCz='m   ';HFz='add-';
-eval "$Az$Bz$z$Cz$Dz$Ez$Fz$z$Gz$Hz$Iz$z$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$Rz$z$Sz$Tz$Uz$Vz$Iz$z$Wz$Xz$Yz$Zz$az$z$bz$cz$Pz$dz$ez$z$fz$gz$hz$iz$z$jz$kz$lz$mz$nz$oz$pz$qz$rz$Rz$z$sz$tz$uz$vz$wz$xz$yz$ABz$BBz$z$CBz$DBz$EBz$FBz$GBz$HBz$IBz$JBz$z$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$XBz$ABz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$z$jBz$kBz$lBz$jBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$z$KBz$uBz$tz$uz$vBz$wBz$xBz$yBz$ACz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$HBz$Rz$z$ICz$JCz$KCz$LCz$z$MCz$NCz$OCz$PCz$QCz$KBz$RCz$SCz$TCz$CBz$UCz$VCz$WCz$XCz$YCz$ZCz$z$aCz$bCz$cCz$dCz$eCz$MCz$fCz$gCz$hCz$z$iCz$jCz$z$kCz$z$iCz$eBz$gz$lCz$mCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$oCz$Uz$Mz$z$iCz$eBz$gz$hz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$xCz$qCz$qCz$yCz$ADz$Rz$z$iCz$eBz$gz$lCz$mCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$oCz$Uz$Mz$z$iCz$eBz$BDz$z$iCz$eBz$CDz$qCz$qCz$DDz$EDz$FDz$GDz$HDz$IDz$JDz$KDz$z$iCz$eBz$CDz$Yz$LDz$MDz$NDz$ODz$PDz$QDz$RDz$Yz$LDz$SDz$TDz$UDz$VDz$WDz$XDz$z$iCz$eBz$CDz$YDz$ZDz$dz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$KDz$z$iCz$eBz$CDz$qCz$qCz$YDz$ZDz$dz$jDz$kDz$lDz$mDz$nDz$Rz$z$iCz$eBz$CDz$oDz$pDz$qDz$rDz$sDz$nDz$tDz$uDz$vDz$wDz$xDz$Rz$z$iCz$eBz$gz$lCz$mCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$nCz$oCz$Uz$Mz$z$yDz$z$AEz$z$BEz$z$ICz$JCz$CEz$z$iCz$eBz$gz$DEz$EEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$GEz$nDz$Rz$z$iCz$eBz$HEz$Zz$IEz$qCz$qCz$qCz$qCz$qCz$JEz$KEz$LEz$qCz$qCz$qCz$MEz$Mz$z$iCz$eBz$gz$DEz$EEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$FEz$GEz$nDz$Rz$z$iCz$eBz$NEz$OEz$PEz$QEz$nDz$REz$SEz$TEz$UEz$VEz$WEz$XEz$KDz$z$iCz$eBz$NEz$OEz$PEz$YEz$nDz$REz$SEz$ZEz$aEz$bEz$cEz$dEz$eEz$XDz$z$iCz$eBz$NEz$OEz$PEz$fEz$nDz$REz$SEz$gEz$hEz$iEz$jEz$kEz$z$iCz$eBz$BDz$z$lEz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$tEz$uEz$vEz$wEz$xEz$yEz$z$AFz$BFz$CFz$DFz$z$EFz$FFz$GFz$z$HFz$IFz$JFz$KFz$z$LFz$z$MFz$FFz$GFz$z$NFz$IFz$JFz$KFz$z$LFz$z$OFz$FFz$GFz$z$PFz$z$LFz$z$QFz$FFz$GFz$z$PFz$z$LFz$z$RFz"
+clear
+RED='\033[0;31m'
+NC='\e[0m'
+gray="\e[1;30m"
+Blue="\033[1;36m"
+GREEN='\033[0;32m'
+grenbo="\033[1;95m"
+YELL='\033[1;33m'
+BGX="\033[42m"
+UPDATE="https://abc.xcodehoster.com/"
+BOT="https://abc.xcodehoster.com/"
+ipsaya=$(cat /usr/bin/ipsave)
+data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
+date_list=$(date +"%Y-%m-%d" -d "$data_server")
+data_ip="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+checking_sc() {
+useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
+if [[ $date_list < $useexp ]]; then
+echo -ne
+else
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e ""
+echo -e "            ${RED}PERMISSION DENIED !${NC}"
+echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
+echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
+echo -e "             \033[0;33mContact Admin :${NC}"
+echo -e "      ${GREEN}WhatsApp${NC} wa.me/6283865719160"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+exit
+fi
+}
+checking_sc
+echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
+echo -e " \e[1;971m                      MENU BOT                \e[0m"
+echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
+echo -e "  ${grenbo}[1]${NC}${YELL} Add Bot Notifikasi${NC}"
+echo -e "  ${grenbo}[2]${NC}${YELL} Delete Bot Notifikasi${NC}"
+echo -e "  ${grenbo}[0]${NC}${YELL} Back To Menu${NC}"
+echo -e ""
+read -p "  Select From Options [ 1 - 2 or 0 ] : " menu
+case $menu in
+1) clear ;
+add-bot-notif
+;;
+2) clear ;
+del-bot-notif
+;;
+0) clear ;
+menu
+;;
+*) clear ;
+menu
+;;
+esac
diff --git a/audit_menu/menu/del-bot-notif b/audit_menu/menu/del-bot-notif
--- a/audit_menu/menu/del-bot-notif
+++ b/audit_menu/menu/del-bot-notif
@@ -1,4 +1,53 @@
-#!/bin/bash
-z="
-";FEz='OTIF';OBz='nt.c';mBz=' $3}';lCz='en B';bDz='F_CL';LEz=' "Yo';Hz='33[3';ZCz=' !${';tz='/'\'')';Oz='ya=$';PBz='om/a';JBz='/raw';Vz='data';JEz='e[0m';EBz='erve';PEz='isti';hCz='$ips';REz='lien';xBz='else';vCz='ermi';nEz=' " "';wCz='ssio';kCz='s be';lFz='oken';jBz=' awk';TBz='izin';AFz='ep -';lDz='ot/b';LFz='sed ';fFz='TIFI';oFz=' " I';GBz='_ip=';Yz='$(cu';rz=' Dat';YEz='Pres';tEz='cut ';yDz='[1;9';TCz=' ${R';uFz='D"';TEz='read';pz=' sed';CDz='Cont';dz=' --s';UCz='ED}P';xEz='KEY=';HBz='"htt';oz='te |';LBz='hubu';iCz='aya ';BDz='ts${';gDz='-E "';MFz='-i "';iDz='t# "';IEz='   \';MCz='OUND';AEz='7;10';wDz='━\03';VFz='bot/';yz='Y-%m';SDz='3263';VBz='"';Iz='2;1m';EDz='Admi';LDz='App$';SCz='"   ';Mz='"; }';YCz='NIED';QFz='tken';ODz='2813';pBz='[ $d';aCz='NC}"';MDz=' wa.';qEz='/.bo';fDz=' -c ';uEz='-d '\''';OCz='OSCR';FFz='c/bo';cFz='ELET';GEz='IKAS';XDz='}';rBz='list';fBz='_ip ';ACz='3[1;';Nz='ipsa';Kz='\\03';OEz='o ex';GFz='t/.b';BEz='1m  ';vBz='hen';Fz=' -e ';YFz='rm -';gBz='| gr';oCz='C}"';QCz=' \03';CEz='DELE';NDz='me/6';vDz='━━━━';aEz='Ente';cBz='(wge';EEz='OT N';iEz='ID=$';KEz=' ""';ZBz=') {';NBz='onte';Ez='echo';cCz='[0;3';cz='cure';KCz='04 N';gEz='menu';VCz='ERMI';NCz=' AUT';cEz='to b';sz='e: /';GDz='{NC}';DEz='TE B';Cz='red(';kEz='p -E';iz='ogle';MEz='u ha';wBz=' -ne';mz=' gre';jDz=' "/e';nFz='EY"';IFz=' cut';RBz='nsto';qFz='legr';xDz='" \e';bEz='r ] ';jFz=' " B';pEz='/bot';sDz='; th';gFz='KASI';Bz='r';fEz='enu"';Tz='save';uCz='ss p';QEz='ng c';JCz='   4';ICz='    ';iBz='ya |';qBz='ate_';cDz='IENT';az='v --';fCz='PS${';NEz='ve n';bBz='xp=$';uz='date';qDz='= '\''0';JDz='EN}W';dBz='t -q';uDz='36m━';KDz='hats';JFz=''\'' '\'' ';UBz='/mai';DCz='───\';DFz='# " ';Sz='n/ip';tFz='HATI';VEz='1 -s';CBz='"$da';lEz=' "^#';BCz='93m─';HDz='   $';WCz='SSIO';PDz='2739';iFz='[0m"';oEz='/etc';kz='/ 2>';RCz='""';FCz='0m"';FDz='n :$';dEz='ack ';oBz='if [';SBz='res/';ABz='-%d"';dDz='S=$(';Uz=')';XEz='-p "';mDz='ot.d';bFz='ES D';XCz='N DE';qz=''\''s/<';BBz=' -d ';aBz='usee';ZEz='s [ ';yEz='$(gr';rFz='am  ';rDz=''\'' ]]';XBz='king';HFz='b" |';eCz='ur V';mCz='anne';HCz='m   ';ez='ilen';ZDz='NUMB';gCz='NC} ';DDz='act ';KBz='.git';OFz='ot# ';wEz='f 3)';LCz='OT F';CCz='────';yBz='"\03';Wz='_ser';xz=' +"%';hEz='CHAT';kDz='tc/b';Qz=' /us';IDz='{GRE';QDz='3959';XFz='.db';uBz=']; t';YBz='_sc(';hDz='^#bo';jCz='3mHa';WBz='chec';sBz=' < $';kFz='ot T';kBz=' '\''{p';nDz='b")';pFz='D Te';PFz='$bot';WEz=' -r ';sFz=': $C';QBz='rivp';eFz='T NO';RDz='6282';Jz='${*}';nBz=''\'')';mEz='bot#';Pz='(cat';BFz='E "^';WFz='.bot';tDz='en';gz='tps:';tBz='xp ]';GCz='3[42';eDz='grep';lBz='rint';Xz='ver=';jz='.com';yCz='or s';UEz=' -n ';ADz='crip';wz='t=$(';WDz='fi';bz='inse';jEz='(gre';dFz='E BO';tCz='acce';dCz='3mYo';fz='t ht';rEz='t.db';lz='&1 |';SFz='min/';NFz='/^#b';TFz='d" /';PCz='IPT ';HEz='I   ';nz='p Da';KFz='-f 2';vEz=' '\'' -';sEz='" | ';IBz='ps:/';qCz='33[0';MBz='serc';YDz='_sc';rCz=';33m';vz='_lis';oDz='[ ${';bCz='\033';nCz='d${N';pCz='  \0';eEz='on m';ECz='033[';Rz='r/bi';xCz='ns f';eBz='O- $';Dz=') { ';CFz='#bot';UDz='0"';aFz='SUCC';EFz='"/et';sCz='Buy ';SEz='ts!"';Zz='rl -';UFz='etc/';TDz='2230';ZFz='rf /';Gz='"\\0';aDz='ER_O';RFz=' $ad';FBz='r")';hBz='ep $';VDz='exit';mFz=': $K';hFz='  \e';hz='//go';Lz='3[0m';pDz='S} =';DBz='ta_s';Az='clea';
-eval "$Az$Bz$z$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$z$Vz$Wz$Xz$Yz$Zz$az$bz$cz$dz$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$Fz$qz$rz$sz$tz$z$uz$vz$wz$uz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$z$Vz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$Sz$VBz$z$WBz$XBz$YBz$ZBz$z$aBz$bBz$cBz$dBz$eBz$Vz$fBz$gBz$hBz$Nz$iBz$jBz$kBz$lBz$mBz$nBz$z$oBz$pBz$qBz$rBz$sBz$aBz$tBz$uBz$vBz$z$Ez$wBz$z$xBz$z$Ez$Fz$yBz$ACz$BCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$DCz$ECz$FCz$z$Ez$Fz$yBz$GCz$HCz$ICz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$ICz$ICz$QCz$Lz$VBz$z$Ez$Fz$yBz$ACz$BCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$DCz$ECz$FCz$z$Ez$Fz$RCz$z$Ez$Fz$SCz$ICz$ICz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$z$Ez$Fz$SCz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$bCz$cCz$jCz$kCz$lCz$mCz$nCz$oCz$z$Ez$Fz$SCz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$xCz$yCz$ADz$BDz$aCz$z$Ez$Fz$SCz$ICz$ICz$pCz$qCz$rCz$CDz$DDz$EDz$FDz$GDz$VBz$z$Ez$Fz$SCz$HDz$IDz$JDz$KDz$LDz$GDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$z$Ez$Fz$yBz$ACz$BCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$CCz$DCz$ECz$FCz$z$VDz$z$WDz$z$XDz$z$WBz$XBz$YDz$z$Az$Bz$z$ZDz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$nDz$z$oBz$oDz$ZDz$aDz$bDz$cDz$pDz$qDz$rDz$sDz$tDz$z$Ez$Fz$yBz$ACz$uDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$wDz$Lz$VBz$z$Ez$Fz$xDz$yDz$AEz$BEz$ICz$ICz$CEz$DEz$EEz$FEz$GEz$HEz$ICz$IEz$JEz$VBz$z$Ez$Fz$yBz$ACz$uDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$wDz$Lz$VBz$z$Ez$KEz$z$Ez$LEz$MEz$NEz$OEz$PEz$QEz$REz$SEz$z$Ez$KEz$z$Ez$Fz$yBz$ACz$uDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$wDz$Lz$VBz$z$TEz$UEz$VEz$WEz$XEz$YEz$ZEz$aEz$bEz$cEz$dEz$eEz$fEz$z$gEz$z$WDz$z$Az$Bz$z$hEz$iEz$jEz$kEz$lEz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$tEz$uEz$vEz$wEz$z$xEz$yEz$AFz$BFz$CFz$DFz$EFz$FFz$GFz$mDz$HFz$IFz$BBz$JFz$KFz$Uz$z$LFz$MFz$NFz$OFz$PFz$QFz$RFz$SFz$TFz$UFz$VFz$WFz$XFz$z$YFz$ZFz$UFz$VFz$WFz$XFz$z$Az$Bz$z$Ez$Fz$yBz$ACz$uDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$wDz$Lz$VBz$z$Ez$Fz$xDz$yDz$AEz$BEz$ICz$aFz$bFz$cFz$dFz$eFz$fFz$gFz$ICz$hFz$iFz$z$Ez$Fz$yBz$ACz$uDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$wDz$Lz$VBz$z$Ez$jFz$kFz$lFz$ICz$mFz$nFz$z$Ez$oFz$pFz$qFz$rFz$sFz$tFz$uFz$z$Ez$Fz$yBz$ACz$uDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$vDz$wDz$Lz$VBz$z$Ez$KEz$z$TEz$UEz$VEz$WEz$XEz$YEz$ZEz$aEz$bEz$cEz$dEz$eEz$fEz$z$gEz"
+clear
+red() { echo -e "\\033[32;1m${*}\\033[0m"; }
+ipsaya=$(cat /usr/bin/ipsave)
+data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
+date_list=$(date +"%Y-%m-%d" -d "$data_server")
+data_ip="$(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip"
+checking_sc() {
+useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
+if [[ $date_list < $useexp ]]; then
+echo -ne
+else
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+echo -e ""
+echo -e "            ${RED}PERMISSION DENIED !${NC}"
+echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
+echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
+echo -e "             \033[0;33mContact Admin :${NC}"
+echo -e "      ${GREEN}WhatsApp${NC} wa.me/62838657191606282326322300"
+echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+exit
+fi
+}
+checking_sc
+clear
+NUMBER_OF_CLIENTS=$(grep -c -E "^#bot# " "/etc/bot/bot.db")
+if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
+echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+echo -e " \e[1;97;101m          DELETE BOT NOTIFIKASI          \e[0m"
+echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+echo ""
+echo "You have no existing clients!"
+echo ""
+echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+read -n 1 -s -r -p "Press [ Enter ] to back on menu"
+menu
+fi
+clear
+CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
+KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
+sed -i "/^#bot# $bottken $admin/d" /etc/bot/.bot.db
+rm -rf /etc/bot/.bot.db
+clear
+echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+echo -e " \e[1;97;101m      SUCCES DELETE BOT NOTIFIKASI      \e[0m"
+echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+echo " Bot Token    : $KEY"
+echo " ID Telegram  : $CHATID"
+echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+echo ""
+read -n 1 -s -r -p "Press [ Enter ] to back on menu"
+menu
diff --git a/audit_menu/menu/lock b/audit_menu/menu/lock
--- a/audit_menu/menu/lock
+++ b/audit_menu/menu/lock
@@ -1,4 +1,132 @@
-#!/bin/bash
-z="
-";Qz='1m${';cDz='p 1';dEz='██10';JIz='etc/';wHz='%2s ';TJz='l $u';CKz=' ser';Gz='e[1;';vz='33[0';lJz=' "';pz='yell';AGz='$spi';Nz='e "\';rJz='Sc_C';XHz=')"';DDz='$(ec';fFz='l pi';GHz='exp=';LCz='an p';EEz=' for';IIz=' < /';Lz='{ ec';yIz='p 3 ';uDz='1"';dCz='-9;]';mDz='xt1=';PIz='k -F';iEz='ames';PBz='32m"';wz=';35m';qCz='- le';sDz='t By';OCz=' yan';NIz='AH="';oEz='rati';EBz='m"';RFz=' ""';fDz='akas';aJz='Be} ';pEz='on))';HBz='33[5';HFz='(i %';BKz='your';oJz='s   ';DFz=')); ';YBz=' bar';PHz='t ex';kGz='ed';lBz='bari';eGz='TUS"';iBz='_Ban';bz='1;1m';QJz=' the';ZDz='it()';aIz='1}'\'' ';PCz='g di';oCz=' (wi';Mz='ho -';TBz='Be="';Kz='n() ';XDz=' Sc_';Hz='32m'\''';YJz='"${G';Az='red=';AFz='_ite';CIz='"UNL';Bz=''\''\e[';uHz='s %-';JJz='wd >';gIz=' Acc';LEz='r/bi';uBz='V4"';cFz='done';vGz='expi';SCz='l pl';cHz=' -S ';YEz='█65%';eHz=' )"';UCz='=$(e';mFz=''\''';HJz='rnam';uCz='prin';kHz=']; t';NBz='Gree';NCz='aris';OHz='coun';AEz='-p "';AJz='& lo';jz='ng..';eEz='0%")';vHz='17s ';UFz=' ${f';jCz='in_t';lCz='l sp';vFz='mp=$';EDz='e "$';SBz=';33m';FBz='Blue';rBz='ARIS';yGz='ep -';cz='${*}';vJz='erna';QIz=': '\''$';oz=' " "';sz='3m"';bFz='5';JGz='elay';XFz='ndex';lHz='hen';JFz='mes)';nJz='tatu';ICz='suai';JDz='\e[3';lFz='-\|/';VBz='4m"';vDz='read';FFz='inde';TFz='de}m';VEz='██35';mJz='w} S';qFz='$pid';LHz='N | ';bEz=' "██';yFz='[%c]';ZFz='[0m"';yEz=' num';PJz='0 ];';nCz='=$((';wBz='ter_';bHz='sswd';rIz='ame ';XJz='er';jIz=' $JU';VCz='cho ';gGz='──┘\';OIz='$(aw';gDz='ih s';MBz='37m"';MJz='l';tBz='NEL ';mGz='="$(';REz='es=(';dIz='swd ';vEz='((i ';xFz='n#?}';RDz='cent';sHz='%-17';EIz='D${N';NDz='MASC';hCz='n=${';MHz='grep';CEz='ss E';eJz='rk} ';ZHz='us="';bCz='\x1b';Dz='m'\''';cJz='lly ';IGz='p $d';mBz='s_pa';Rz='*}\\';fHz='if [';xCz='pace';nGz=' $ex';mHz='[ "$';cCz='\[[0';lDz='- \0';bBz='ng()';NJz=' $? ';EHz='d: -';HEz=' Man';bIz='/etc';ZIz='nt $';Jz='\e[0';qEz='Load';YIz='{pri';TCz='ain_';tz='ungu';SJz='wd -';NEz='ssh';THz=': " ';aFz='p 0.';YCz='t" |';HIz='fi';jGz='xpir';CHz=' | c';JEz='bash';uFz='; do';bDz='slee';jFz='0.1';pHz='" ]]';KBz='eBe=';sBz='CTUN';DCz='$1"';mEz='ns=$';mz='clea';WFz='s[$i';OGz='_Suc';dHz='awk ';iCz='#pla';pBz='NAMA';OEz='dura';lEz='atio';mIz='ser"';ABz='"\03';ODz=' \e[';DBz='Xark';kCz='ext}';xIz='name';aDz='{';xBz='text';UJz='ame';GCz='50  ';GGz='$tem';nDz='3[0;';NFz='((31';hDz='udah';sJz='t';QGz=' "\0';BIz='  " ';SHz=' -F"';wGz='red ';TEz='0%" ';CCz='xt="';HDz='atte';fEz='num_';FHz='f3)"';tJz='else';ZJz='reen';QFz='))';SIz=' 100';aGz='E   ';YFz=']}\e';VFz='rame';UDz='"$fo';Xz='echo';kJz='ark}';GIz='L}"';pIz='ut U';cEz='███9';lGz='AKUN';lIz='   u';OFz=' + i';iJz=' : $';DIz='OCKE';qHz='; th';oDz='35m ';sFz='dev/';yDz=' -r ';tIz='want';LDz=':.\0';GDz='form';yBz='() {';EFz='do';Ez='gree';ZEz='" "█';eBz='————';YGz=' USE';WBz='func';wEz='= 0;';nHz='us" ';kIz='MLAH';cGz='DATE';jBz='ner(';dJz='${Xa';NGz='ding';MGz=' Loa';hIz='ount';KGz='\b\b';sGz='-f1)';uz='="\0';UGz='36m┌';CDz='"" "';VIz='!= "';DJz='es';xHz='"  $';QEz='fram';hGz='e re';WDz='ted_';iDz=' men';nFz='whil';ZCz=' sed';qIz='sern';IEz='age"';IDz='d_te';BEz=' Pre';pJz=' : L';CGz='in=$';pDz='Scri';tCz=')';WEz='%" "';eFz='ing(';sIz='you ';rFz=' > /';xGz='| gr';SDz='er_t';UBz='[5;3';hHz='D -g';xEz=' i <';gEz='es=$';dGz=' STA';fGz='36m└';rGz='-d: ';dz='\\03';LGz='    ';YDz='Cred';UIz=' $1 ';cBz=' {';wJz='me n';vBz=' cen';wDz=' -n ';FEz=' Bac';Cz='1;31';oBz='g';RGz=';32m';wFz='{spi';DEz='nter';XGz=' "  ';gCz='l le';MDz=' $NA';xz='"';qBz='SC="';rHz='en';WHz='$2}'\''';xJz='ot f';Uz=' }';AIz='exp ';kEz='iter';CFz=' i++';tHz='s %2';Iz='NC='\''';vIz='lock';VHz='int ';fJz='"${y';XEz='████';BCz='l te';BDz='\n" ';bGz='EXP ';jJz=' ${X';ADz='s\03';WCz='-e "';Oz='\033';nBz='njan';MFz='de=$';Wz=') { ';gFz='d=$1';hEz='{#fr';Zz='"\\0';BJz='adin';dBz='36m ';eDz='erim';Vz='red(';GJz='$use';fIz=' -l)';GEz='k to';qJz='D!! ';KCz='deng';fCz='g'\'')';gBz='}';WGz='──┐\';wIz='user';jDz='ggun';tDz=' \03';oHz='= "P';kDz='akan';QHz='s" |';UEz='"███';Sz='033[';pGz='d | ';PFz=' % 7';UHz=''\''{pr';tFz='null';pCz='dth ';dDz='5m T';QDz='::."';oGz='pire';KDz='6m.:';DKz='ver.';FJz='p "^';ZBz='is_p';Pz='[32;';tEz='asi(';SFz='1;${';JCz='kan ';RHz=' awk';az='33[3';rCz='n) /';WJz='Bann';iIz='ber:';Yz=' -e ';qz='ow="';nz='r';sEz='Anim';EGz='${sp';Tz='0m";';OBz='nBe=';IJz='e" /';mCz='aces';DGz='temp';aHz='$(pa';yHz='" "$';YHz='stat';ACz='loca';IBz=';36m';kBz=') {';lz='0m"';PGz='ces(';nIz='""';OJz='-eq ';FCz='dth=';uGz='ho $';sCz=' 2 )';Fz='n='\''\';XIz='dy" ';EJz='egre';KEz=' /us';kz='.\e[';JBz='Whit';iz='oadi';SEz='"██1';TIz='0 &&';MIz='JUML';rEz='ing_';HHz='"$(c';TDz='ext ';KIz='pass';CJz='g $!';CBz=';1m"';QCz='ingi';HGz='p"}';aBz='anja';aCz=' '\''s/';TGz='es\0';ZGz='RNAM';PEz='=3';iFz='lay=';pFz=' -p ';IFz='_fra';gz='"\e[';PDz='36m.';LIz='wd';eCz='*m//';yJz='ound';jHz='00 ]';RBz='owBe';VJz='ARI_';wCz='%${s';hJz='w} U';VDz='rmat';WIz='nobo';LFz='r_co';kFz='in='\''';oFz='e ps';uEz='for ';hFz='l de';fBz='———\';MCz='ng b';FGz='in%"';bJz='esfu';DHz='ut -';yz='Red=';vCz='tf "';yCz='s}s%';iHz='e 10';BFz='ons;';qGz='cut ';VGz='────';hBz=' ARI';xDz='1 -s';eIz='| wc';iGz='ad e';FDz='")"';cIz='/pas';rz='[0;3';MEz='n/m-';KJz='/dev';gJz='ello';BGz='n"';AHz='v no';IHz='hage';KHz='$AKU';qDz='pt C';LJz='/nul';uJz=' "Us';dFz='load';RJz='n';AKz=' on ';hz='32ml';QBz='Yell';tGz='ID="';ECz='l wi';oIz='"Inp';SGz='Succ';XCz='$tex';gHz='[ $I';fz='"; }';GFz='x=$(';RCz='nkan';LBz='3[5;';RIz='3 >=';jEz='[@]}';uIz=' to ';KFz='colo';HCz='# Se';FIz='ORMA';BBz='3[91';aEz='80%"';XBz='tion';NHz=' "Ac';GBz='Cyan';JHz=' -l ';rDz='redi';ez='3[0m';nEz='((du';BHz='body';
-eval "$Az$Bz$Cz$Dz$z$Ez$Fz$Gz$Hz$z$Iz$Jz$Dz$z$Ez$Kz$Lz$Mz$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$z$Vz$Wz$Xz$Yz$Zz$az$bz$cz$dz$ez$fz$z$Xz$Yz$gz$hz$iz$jz$kz$lz$z$mz$nz$z$Xz$oz$z$mz$nz$z$pz$qz$Oz$rz$sz$z$tz$uz$vz$wz$xz$z$yz$ABz$BBz$CBz$z$DBz$uz$vz$EBz$z$FBz$GBz$uz$HBz$IBz$xz$z$JBz$KBz$ABz$LBz$MBz$z$NBz$OBz$ABz$LBz$PBz$z$QBz$RBz$uz$HBz$SBz$xz$z$FBz$TBz$Oz$UBz$VBz$z$WBz$XBz$YBz$ZBz$aBz$bBz$cBz$z$Xz$Yz$ABz$LBz$dBz$eBz$eBz$eBz$eBz$eBz$eBz$eBz$eBz$eBz$eBz$eBz$fBz$Sz$lz$z$gBz$z$WBz$XBz$hBz$iBz$jBz$kBz$z$lBz$mBz$nBz$oBz$z$pBz$qBz$rBz$sBz$tBz$uBz$z$WBz$XBz$vBz$wBz$xBz$yBz$z$ACz$BCz$CCz$DCz$z$ACz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$aBz$MCz$NCz$OCz$PCz$QCz$RCz$z$ACz$SCz$TCz$xBz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$z$ACz$gCz$hCz$iCz$jCz$kCz$z$ACz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$tCz$z$uCz$vCz$wCz$xCz$yCz$ADz$ez$BDz$CDz$DDz$Mz$EDz$xBz$FDz$z$gBz$z$GDz$HDz$IDz$CCz$JDz$KDz$LDz$vz$wz$MDz$NDz$ODz$PDz$QDz$z$RDz$SDz$TDz$UDz$VDz$WDz$xBz$xz$z$lBz$mBz$nBz$oBz$z$gBz$z$WBz$XBz$XDz$YDz$ZDz$aDz$z$bDz$cDz$z$lBz$mBz$nBz$oBz$z$WBz$XBz$vBz$wBz$xBz$yBz$z$ACz$BCz$CCz$DCz$z$ACz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$aBz$MCz$NCz$OCz$PCz$QCz$RCz$z$ACz$SCz$TCz$xBz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$z$ACz$gCz$hCz$iCz$jCz$kCz$z$ACz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$tCz$z$uCz$vCz$wCz$xCz$yCz$ADz$ez$BDz$CDz$DDz$Mz$EDz$xBz$FDz$z$gBz$z$GDz$HDz$IDz$CCz$Oz$rz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$vz$EBz$z$GDz$HDz$IDz$mDz$ABz$nDz$oDz$pDz$qDz$rDz$sDz$MDz$NDz$tDz$ez$xz$z$RDz$SDz$TDz$UDz$VDz$WDz$xBz$xz$z$RDz$SDz$TDz$UDz$VDz$WDz$xBz$uDz$z$lBz$mBz$nBz$oBz$z$vDz$wDz$xDz$yDz$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$z$JEz$KEz$LEz$MEz$NEz$z$gBz$z$OEz$XBz$PEz$z$QEz$REz$SEz$TEz$UEz$VEz$WEz$XEz$XEz$YEz$ZEz$XEz$XEz$XEz$aEz$bEz$XEz$XEz$XEz$XEz$cEz$TEz$UEz$XEz$XEz$XEz$XEz$XEz$dEz$eEz$z$fEz$QEz$gEz$hEz$iEz$jEz$z$fEz$kEz$lEz$mEz$nEz$oEz$pEz$z$qEz$rEz$sEz$tEz$kBz$z$uEz$vEz$wEz$xEz$yEz$AFz$oEz$BFz$CFz$DFz$EFz$z$mz$nz$z$FFz$GFz$HFz$yEz$IFz$JFz$tCz$z$KFz$LFz$MFz$NFz$OFz$PFz$QFz$z$Xz$RFz$z$Xz$RFz$z$Xz$RFz$z$Xz$Yz$gz$SFz$KFz$LFz$TFz$UFz$VFz$WFz$XFz$YFz$ZFz$z$bDz$aFz$bFz$z$cFz$z$gBz$z$dFz$eFz$kBz$z$ACz$fFz$gFz$z$ACz$hFz$iFz$jFz$z$ACz$lCz$kFz$lFz$mFz$z$nFz$oFz$pFz$qFz$rFz$sFz$tFz$uFz$z$ACz$BCz$vFz$wFz$xFz$z$uCz$vCz$yFz$oz$AGz$BGz$z$ACz$lCz$CGz$DGz$EGz$FGz$GGz$HGz$z$bDz$IGz$JGz$z$uCz$vCz$KGz$KGz$KGz$xz$z$cFz$z$uCz$vCz$LGz$KGz$KGz$xz$z$gBz$z$WBz$XBz$MGz$NGz$OGz$PGz$kBz$z$mz$nz$z$Xz$Yz$QGz$HBz$RGz$SGz$TGz$vz$EBz$z$bDz$cDz$z$mz$nz$z$gBz$z$Xz$Yz$ABz$LBz$UGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$WGz$Sz$lz$z$Xz$XGz$YGz$ZGz$aGz$LGz$bGz$cGz$LGz$LGz$dGz$eGz$z$Xz$Yz$ABz$LBz$fGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$gGz$Sz$lz$z$Xz$Yz$ABz$LBz$UGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$WGz$Sz$lz$z$nFz$hGz$iGz$jGz$kGz$z$EFz$z$lGz$mGz$Xz$nGz$oGz$pGz$qGz$rGz$sGz$xz$z$tGz$DDz$uGz$vGz$wGz$xGz$yGz$AHz$BHz$CHz$DHz$EHz$FHz$z$GHz$HHz$IHz$JHz$KHz$LHz$MHz$NHz$OHz$PHz$oGz$QHz$RHz$SHz$THz$UHz$VHz$WHz$XHz$z$YHz$ZHz$aHz$bHz$cHz$KHz$LHz$dHz$UHz$VHz$WHz$eHz$z$fHz$gHz$hHz$iHz$jHz$kHz$lHz$z$fHz$mHz$YHz$nHz$oHz$pHz$qHz$rHz$z$uCz$vCz$sHz$tHz$uHz$vHz$wHz$BDz$xHz$lGz$yHz$AIz$BIz$CIz$DIz$EIz$FIz$GIz$z$HIz$z$HIz$z$cFz$IIz$JIz$KIz$LIz$z$MIz$NIz$OIz$PIz$QIz$RIz$SIz$TIz$UIz$VIz$WIz$XIz$YIz$ZIz$aIz$bIz$cIz$dIz$eIz$fIz$xz$z$Xz$Yz$ABz$LBz$fGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$gGz$Sz$lz$z$Xz$Yz$ABz$LBz$UGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$WGz$Sz$lz$z$Xz$XGz$gIz$hIz$yEz$iIz$jIz$kIz$lIz$mIz$z$Xz$Yz$ABz$LBz$fGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$VGz$gGz$Sz$lz$z$Xz$Yz$nIz$z$vDz$pFz$oIz$pIz$qIz$rIz$sIz$tIz$uIz$vIz$THz$wIz$xIz$z$bDz$yIz$AJz$BJz$CJz$z$qEz$rEz$SGz$DJz$z$EJz$FJz$GJz$HJz$IJz$JIz$KIz$JJz$KJz$LJz$MJz$z$fHz$NJz$OJz$PJz$QJz$RJz$z$KIz$SJz$TJz$qIz$UJz$z$mz$nz$z$VJz$WJz$XJz$z$Xz$oz$z$lBz$mBz$nBz$oBz$z$Xz$Yz$YJz$ZJz$aJz$SGz$bJz$cJz$dJz$eJz$xz$z$Xz$Yz$nIz$z$Xz$Yz$fJz$gJz$hJz$qIz$rIz$iJz$wIz$xIz$jJz$kJz$lJz$z$Xz$Yz$fJz$gJz$mJz$nJz$oJz$pJz$DIz$qJz$dJz$eJz$xz$z$Xz$Yz$nIz$z$lBz$mBz$nBz$oBz$z$rJz$rDz$sJz$z$tJz$z$Xz$uJz$vJz$wJz$xJz$yJz$AKz$BKz$CKz$DKz$xz$z$HIz"
+red='\e[1;31m'
+green='\e[1;32m'
+NC='\e[0m'
+green() { echo -e "\\033[32;1m${*}\\033[0m"; }
+red() { echo -e "\\033[31;1m${*}\\033[0m"; }
+echo -e "\e[32mloading...\e[0m"
+clear
+echo " "
+clear
+yellow="\033[0;33m"
+ungu="\033[0;35m"
+Red="\033[91;1m"
+Xark="\033[0m"
+BlueCyan="\033[5;36m"
+WhiteBe="\033[5;37m"
+GreenBe="\033[5;32m"
+YellowBe="\033[5;33m"
+BlueBe="\033[5;34m"
+function baris_panjang() {
+echo -e "\033[5;36m ———————————————————————————————————————————————\033[0m"
+}
+function ARI_Banner() {
+baris_panjang
+NAMASC="Si Cepat VPN"
+function center_text() {
+local text="$1"
+local width=50  # Sesuaikan dengan panjang baris yang diinginkan
+local plain_text=$(echo -e "$text" | sed 's/\x1b\[[0-9;]*m//g')
+local len=${#plain_text}
+local spaces=$(( (width - len) / 2 ))
+printf "%${spaces}s%s\033[0m\n" "" "$(echo -e "$text")"
+}
+formatted_text="\e[36m.::.\033[0;35m $NAMASC \e[36m.::."
+center_text "$formatted_text"
+baris_panjang
+}
+function Sc_Credit(){
+sleep 1
+baris_panjang
+function center_text() {
+local text="$1"
+local width=50  # Sesuaikan dengan panjang baris yang diinginkan
+local plain_text=$(echo -e "$text" | sed 's/\x1b\[[0-9;]*m//g')
+local len=${#plain_text}
+local spaces=$(( (width - len) / 2 ))
+printf "%${spaces}s%s\033[0m\n" "" "$(echo -e "$text")"
+}
+formatted_text="\033[0;35m Terimakasih sudah menggunakan- \033[0m"
+formatted_text1="\033[0;35m Script Credit By $NAMASC \033[0m"
+center_text "$formatted_text"
+center_text "$formatted_text1"
+baris_panjang
+read -n 1 -s -r -p " Press Enter for Back to Manage"
+bash /usr/bin/m-ssh
+}
+duration=3
+frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")
+num_frames=${#frames[@]}
+num_iterations=$((duration))
+Loading_Animasi() {
+for ((i = 0; i < num_iterations; i++)); do
+clear
+index=$((i % num_frames))
+color_code=$((31 + i % 7))
+echo ""
+echo ""
+echo ""
+echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
+sleep 0.5
+done
+}
+loading() {
+local pid=$1
+local delay=0.1
+local spin='-\|/'
+while ps -p $pid > /dev/null; do
+local temp=${spin#?}
+printf "[%c] " "$spin"
+local spin=$temp${spin%"$temp"}
+sleep $delay
+printf "\b\b\b\b\b\b"
+done
+printf "    \b\b\b\b"
+}
+function Loading_Succes() {
+clear
+echo -e  "\033[5;32mSucces\033[0m"
+sleep 1
+clear
+}
+echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
+echo "   USERNAME       EXP DATE         STATUS"
+echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
+echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
+while read expired
+do
+AKUN="$(echo $expired | cut -d: -f1)"
+ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
+exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
+status="$(passwd -S $AKUN | awk '{print $2}' )"
+if [[ $ID -ge 1000 ]]; then
+if [[ "$status" = "P" ]]; then
+printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
+fi
+fi
+done < /etc/passwd
+JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
+echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
+echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
+echo "   Account number: $JUMLAH   user"
+echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
+echo -e ""
+read -p "Input Username you want to lock: " username
+sleep 3 & loading $!
+Loading_Succes
+egrep "^$username" /etc/passwd >/dev/null
+if [ $? -eq 0 ]; then
+passwd -l $username
+clear
+ARI_Banner
+echo " "
+baris_panjang
+echo -e "${GreenBe} Succesfully ${Xark} "
+echo -e ""
+echo -e "${yellow} Username  : $username ${Xark} "
+echo -e "${yellow} Status    : LOCKED!! ${Xark} "
+echo -e ""
+baris_panjang
+Sc_Credit
+else
+echo "Username not found on your server."
+fi
diff --git a/audit_menu/menu/restorefile b/audit_menu/menu/restorefile
--- a/audit_menu/menu/restorefile
+++ b/audit_menu/menu/restorefile
@@ -1,4 +1,156 @@
-#!/bin/bash
-z="
-";LLz='" Se';VEz=';35m';gMz='rror';DDz='V4"';KCz='expo';Cz='3[0;';WLz='="/r';lMz='wnlo';gBz='(gre';EIz='Wait';RGz='kup}';XMz=' Dow';uHz=' the';rBz='-d '\''';Pz='"';fMz='le E';vCz='njan';LFz='ID="';mHz='g to';WIz='c/ &';lz='=$(c';gz='1m" ';AMz='le N';qz='ve)';kIz='dev/';PLz='ile ';hHz='er p';CGz='ain}';pIz='cp -';UMz='hen';hCz='"\03';dMz='${NC';LJz='s.db';RIz='ng p';bFz='━◇</';mMz='aded';NIz='d /e';KMz=' : "';YBz='ep $';iEz='Cred';UCz='$KEY';SMz=' 2>&';HHz=' Dat';Rz='n='\''\';pBz='" | ';LEz='$(ec';HIz='In P';GIz='ing ';MMz='get ';MDz='l wi';NLz='our ';hJz='r ba';dCz='ng()';vGz='ull';RLz='g Te';VGz='ne</';BGz='{dom';RMz=' > /';fz='[44;';hLz='File';nBz='/.bo';oDz='l le';hMz='"The';yKz='rted';mGz='=$TE';RJz='an.d';hIz='ow /';KGz='{dat';FEz='pace';DKz='yt/v';AIz='/bac';cGz='t_id';KEz='"" "';vBz='$(gr';PFz='Y"';MCz='IME=';kLz='d${N';MEz='ho -';Yz='2;1m';RFz='="$T';YFz='<cod';dz='BG_B';sDz='ext}';mCz='}';lCz='———\';nMz='. Pl';rIz='t /v';MHz='r da';wCz='g';ZFz='e>◇━';fCz='echo';dBz='2}'\'')';lEz='p 1';eJz='/dev';QJz='troj';RCz='tele';XLz='ip"';CFz='redi';WBz='/ip ';xLz='acku';yEz='35m ';xIz='ml /';SCz='gram';Xz='\e[9';JDz='l te';cBz='nt $';DEz='tf "';FCz='b" |';YMz='nloa';cKz='n/m-';kCz='————';IHz='a...';CLz='osti';oCz='_Ban';bKz='r/bi';mDz='*m//';EHz='{NC}';hDz=' sed';oBz='t.db';bBz='{pri';oKz='fi';hFz='ORE ';sLz='l 2>';tLz='&1';KFz='p 2';gGz='able';qDz='#pla';nJz='h /e';jMz='s no';LIz='cp p';OCz='rt U';yLz='p Fi';PKz=' -r ';DFz='t By';WMz='REEN';jGz='e_pr';VBz='main';nHz=' dat';REz='d_te';nDz='g'\'')';oFz='re V';OKz='1 -s';ALz='" fi';qJz='r tr';vJz='sock';kDz='\[[0';xJz='r va';SLz='rmin';Fz='\033';aCz=' bar';DHz='NFO$';TGz='e Vp';IDz='loca';lJz='txt ';mBz='/bot';OFz='"$KE';XDz='g di';sFz='SERN';bJz='mit ';aGz='me $';iMz='e wa';nCz=' ARI';AGz='N   ';eDz='-e "';AJz='www/';pJz='ess ';LKz='e...';rMz='link';yGz='Bot(';OJz='vles';vKz='e to';LDz='$1"';mEz='[0;3';cCz='anja';UHz='oot/';kBz=' " "';dGz='=$CH';cDz='=$(e';eMz='}"';TEz='6m.:';rCz='clea';yJz='r.tx';tGz=' >/d';PJz='c/vl';oLz='ot';wJz='s /e';EDz=' cen';KIz='. "';TMz='1; t';Sz='033[';nFz='il R';pHz='f /r';GLz='ink)';bCz='is_p';pCz='ner(';ZBz=' | a';SDz='deng';GHz=' Res';wEz='m"';vFz='{Nam';iFz='NOTI';TFz='URL=';qIz='r ky';ICz=''\'' '\'' ';MJz='c/vm';Kz='0m"';yDz='- le';PIz='&>/d';QGz='ebac';dIz='w /e';Tz='0;32';cJz='/kyt';uJz='adow';pGz='_mod';tEz='ggun';FLz='ct l';HFz='if_r';PEz='form';WKz='k to';NFz='TID"';gHz='ooth';aIz='ng g';NDz='dth=';PGz='{fil';BNz='the ';OGz='ILE ';UGz='s Do';iHz='roce';OMz='$fil';kKz='then';WHz='up.z';iDz=' '\''s/';DBz=' +"%';ADz='ARIS';cz=''\''';Uz='m'\''';Hz='gray';eEz='"$fo';uDz='aces';aEz='::."';MBz='ubus';Vz='gren';vLz='"${R';mz='at /';iLz=' Det';sKz='" "';FGz='P   ';Oz=';34m';XBz='| gr';xBz='E "^';lGz='w=1&';qGz='e=ht';PDz='# Se';uIz='r xr';ANz='to d';UFz='"$UR';iKz='ass ';qLz='f_re';ACz='# " ';mJz='r ss';mIz='ow d';yCz='SC="';sJz='r vl';NCz='"10"';uEz='akan';WGz='curl';BHz='{gre';jEz='it()';YDz='ingi';cLz='n';DNz=' try';oIz='.."';dEz='ext ';FJz='cp c';EKz='ar.t';aLz='ile"';wBz='ep -';fGz='&dis';dHz='dela';qBz='cut ';SKz='ss E';CJz='bot.';vDz='=$((';QEz='atte';wLz='ED}B';sz='(wge';BLz='le h';wMz='r${N';WJz='rf q';ez='LU="';jCz='36m ';fLz='}Bac';gKz=' $In';DGz='</b>';lDz='-9;]';RKz=' Pre';eLz='reen';jBz='bot#';tBz='f 3)';MFz='$CHA';JGz='ODAY';pMz=' che';JIz='ow..';aHz=' # A';iCz='3[5;';AFz='Scri';KBz='raw.';Mz='="\0';VLz='file';DCz='t/.b';wz='azip';aFz='━━━━';XFz='="';SFz='IME"';uCz='s_pa';GJz='ront';nLz='oreB';TCz='.org';MKz='read';cMz='ully';IBz='http';LHz=' you';SEz='\e[3';YGz='--ma';BMz='ot D';WCz='dMes';ULz='pp"';lLz='C}"';XHz='ip &';GCz=' cut';Az='RED=';SIz='d da';jLz='ecte';vEz='- \0';CNz=' and';TBz='es/i';uLz='else';TJz='tc/t';aDz='l pl';xHz='cd /';PMz='e" "';VDz='aris';OLz='up f';SHz='tPas';sCz='r';gFz='REST';gCz=' -e ';YEz=' \e[';wGz=' res';cHz='g a ';mLz='rest';tIz='ib/ ';VMz='"${G';bEz='cent';WEz=' $NA';CMz='etec';NBz='erco';rFz='<b>U';WDz=' yan';PHz='7z x';HMz=' -p ';pEz='akas';BFz='pt C';AEz='n) /';aMz='Succ';yIz='var/';bz=';33m';XEz='MASC';YHz='> /d';pDz='n=${';GBz='Name';qMz='ck y';UJz='roja';SBz='stor';bGz='"cha';lBz='/etc';LGz='eTod';rLz='e > ';Lz='Blue';rEz='udah';CCz='c/bo';aKz=' /us';qKz='Bann';sIz='ar/l';sGz='$URL';kz='MYIP';yz=')';HKz='f ba';NHz='ta..';CIz=' Ple';jDz='\x1b';IMz='"You';iJz='ckup';YCz='func';eKz='if [';wKz=' a s';QCz='api.';xGz='tore';tKz='" Up';xCz='NAMA';eIz='ng s';ODz='50  ';CHz='en}I';dJz='/ &>';QMz='kup"';VHz='back';iGz='_pag';JMz='nk  ';ZEz='36m.';TLz='us A';ZCz='tion';tFz='AME ';BKz='sr/b';gIz='shad';cEz='er_t';kFz='/b>';uKz='load';fHz='r sm';rDz='in_t';yMz='led ';NJz='ess/';kJz='ner.';GDz='text';sBz=' '\'' -';jFz='F⚠️<';BDz='CTUN';wIz='r ht';Dz='31m'\''';QKz='-p "';VFz='L"';xKz='uppo';dDz='cho ';DJz='db /';vHz=' fil';BBz='Toda';DIz='ase ';GKz='rf /';OEz='")"';az='='\''\0';kMz='t do';FHz=' ] •';mKz='ri12';qCz=') {';FBz='-%d"';SGz='e>Re';Bz=''\''\03';RHz='Inpu';uMz='oad ';ZDz='nkan';oz='bin/';dKz='bkp';VJz='n/ &';lFz='    ';IEz='3[0m';ZIz='ll';UDz='ng b';jJz='/ban';sHz='remo';FMz='er y';oJz='r vm';YLz='[ -f';BCz='"/et';UIz='roup';TKz='nter';IKz='.zip';NMz='-O "';FIz=', Re';fEz='rmat';GFz=' not';HBz='url ';yFz='OMAI';JKz=' Don';wHz='e';gLz='kup ';JLz='r   ';bHz='ddin';tz='t -q';mFz='Deta';RBz='ivpn';xDz='dth ';eFz='<b> ';nKz='3Ok"';qHz='y af';gJz='l';JFz='re()';vIz='ay /';fJz='/nul';gDz='t" |';VIz=' /et';vz='canh';IGz='<b>T';rz='IP=$';VCz='/sen';fDz='$tex';oGz='arse';bLz=' ]];';BIz='kup';ABz='date';sEz=' men';ZMz='ded ';hz='# BG';cFz='code';PBz='t.co';MIz='assw';cIz='hado';fBz='ID=$';XCz='sage';NGz='<b>F';pz='ipsa';jIz=' &>/';xz='.com';QDz='suai';Ez='NC='\''';MLz='nd y';HLz='"   ';hBz='p -E';rHz='ter ';sMz='ED}D';jKz=']]; ';QIz='tori';IJz='ssh.';uz='O- i';CBz='y=$(';DLz='ng (';eCz=' {';nIz='ata.';wFz='e}</';KDz='xt="';EEz='%${s';bDz='ain_';OIz='tc/ ';hEz=' Sc_';kGz='evie';BEz=' 2 )';OBz='nten';Zz='YELL';fIz='w da';jHz='ss';AHz='"[ $';gEz='ted_';oEz='erim';XJz='t/* ';Qz='gree';xFz='<b>D';Wz='bo="';XIz='>/de';kEz='slee';eHz='y fo';FKz='xt &';Gz='[0m'\''';jz='U';Iz='="\e';iBz=' "^#';FDz='ter_';NKz=' -n ';uFz=' : $';tJz='r sh';iIz='etc/';kHz=' Sta';ZKz='bash';ZJz='it &';ZGz='x-ti';EJz='bot/';CEz='prin';yHz='root';THz='s /r';oHz='rm -';pFz='PS</';nGz='XT&p';tCz='bari';yBz='#bot';EBz='Y-%m';dFz='>';QHz=' -p$';KKz='e Re';AKz='t /u';HGz='P}</';XKz=' Man';LMz='if w';YIz='v/nu';ELz='dire';Nz='33[0';Jz='[1;3';vMz='Erro';KJz='vmes';DMz='ted$';KHz='ting';nEz='5m T';EGz='<b>I';HEz='s\03';TIz='cp g';tMz='ownl';LCz='rt T';NEz='e "$';JHz=' Get';VKz=' Bac';nz='usr/';MGz='ay}<';ZLz=' "$f';xEz='xt1=';HJz='ab /';eGz='ATID';qEz='ih s';IFz='esto';HCz=' -d ';ECz='ot.d';QFz='TIME';dLz='"${g';uGz='ev/n';tDz='l sp';bIz='cp s';OHz='."';qFz='b>';xMz='"Fai';QLz='usin';FNz='in."';ENz=' aga';wDz=' (wi';rJz='ojan';PCz='RL="';YJz='/lim';TDz='an p';iz=' BIR';JCz='-f 2';EFz=' \03';LBz='gith';HDz='() {';IIz='ss N';JJz='ssh/';BJz='cp .';UEz=':.\0';tHz='ving';ZHz='p 1 ';UBz='zin/';hKz='putP';fKz='[ -z';GEz='s}s%';pKz='ARI_';QBz='m/ar';JEz='\n" ';aBz='wk '\''';lKz='s="A';GMz='ink"';WFz='TEXT';lIz='null';CKz='in/k';eBz='CHAT';UKz=' for';aJz='r li';rKz='er';EMz='"Ent';KLz=' "';lHz='rtin';XGz=' -s ';uBz='KEY=';pLz='noti';RDz='kan ';bMz='essf';CDz='NEL ';SJz='b /e';YKz='age"';GGz='{MYI';JBz='s://';oMz='ease';fFz=' ⚠️ ';FFz='1"';rGz='ml" ';hGz='_web';ILz='   o';
-eval "$Az$Bz$Cz$Dz$z$Ez$Fz$Gz$z$Hz$Iz$Jz$Kz$z$Lz$Mz$Nz$Oz$Pz$z$Qz$Rz$Sz$Tz$Uz$z$Vz$Wz$Xz$Yz$Pz$z$Zz$az$Nz$bz$cz$z$dz$ez$Fz$fz$gz$hz$iz$jz$z$kz$lz$mz$nz$oz$pz$qz$z$rz$sz$tz$uz$vz$wz$xz$yz$z$ABz$BBz$CBz$ABz$DBz$EBz$FBz$yz$z$GBz$lz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$XBz$YBz$kz$ZBz$aBz$bBz$cBz$dBz$z$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$z$uBz$vBz$wBz$xBz$yBz$ACz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$yz$z$KCz$LCz$MCz$NCz$z$KCz$OCz$PCz$IBz$JBz$QCz$RCz$SCz$TCz$mBz$UCz$VCz$WCz$XCz$Pz$z$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$z$fCz$gCz$hCz$iCz$jCz$kCz$kCz$kCz$kCz$kCz$kCz$kCz$kCz$kCz$kCz$kCz$lCz$Sz$Kz$z$mCz$z$YCz$ZCz$nCz$oCz$pCz$qCz$z$rCz$sCz$z$tCz$uCz$vCz$wCz$z$xCz$yCz$ADz$BDz$CDz$DDz$z$YCz$ZCz$EDz$FDz$GDz$HDz$z$IDz$JDz$KDz$LDz$z$IDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$cCz$UDz$VDz$WDz$XDz$YDz$ZDz$z$IDz$aDz$bDz$GDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$nDz$z$IDz$oDz$pDz$qDz$rDz$sDz$z$IDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$BEz$yz$z$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$GDz$OEz$z$mCz$z$PEz$QEz$REz$KDz$SEz$TEz$UEz$Nz$VEz$WEz$XEz$YEz$ZEz$aEz$z$bEz$cEz$dEz$eEz$fEz$gEz$GDz$Pz$z$tCz$uCz$vCz$wCz$z$mCz$z$YCz$ZCz$hEz$iEz$jEz$eCz$z$kEz$lEz$z$tCz$uCz$vCz$wCz$z$YCz$ZCz$EDz$FDz$GDz$HDz$z$IDz$JDz$KDz$LDz$z$IDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$cCz$UDz$VDz$WDz$XDz$YDz$ZDz$z$IDz$aDz$bDz$GDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$nDz$z$IDz$oDz$pDz$qDz$rDz$sDz$z$IDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$BEz$yz$z$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$GDz$OEz$z$mCz$z$PEz$QEz$REz$KDz$Fz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$tEz$uEz$vEz$Nz$wEz$z$PEz$QEz$REz$xEz$hCz$Cz$yEz$AFz$BFz$CFz$DFz$WEz$XEz$EFz$IEz$Pz$z$bEz$cEz$dEz$eEz$fEz$gEz$GDz$Pz$z$bEz$cEz$dEz$eEz$fEz$gEz$GDz$FFz$z$tCz$uCz$vCz$wCz$z$mCz$z$YCz$ZCz$GFz$HFz$IFz$JFz$eCz$z$kEz$KFz$z$eBz$LFz$MFz$NFz$z$uBz$OFz$PFz$z$QFz$RFz$SFz$z$TFz$UFz$VFz$z$WFz$XFz$z$YFz$ZFz$aFz$aFz$aFz$bFz$cFz$dFz$z$eFz$fFz$gFz$hFz$iFz$jFz$kFz$z$eFz$lFz$mFz$nFz$IFz$oFz$pFz$qFz$z$YFz$ZFz$aFz$aFz$aFz$bFz$cFz$dFz$z$rFz$sFz$tFz$uFz$vFz$wFz$qFz$z$xFz$yFz$AGz$uFz$BGz$CGz$DGz$z$EGz$FGz$lFz$uFz$GGz$HGz$qFz$z$IGz$JGz$lFz$uFz$KGz$LGz$MGz$kFz$z$NGz$OGz$lFz$uFz$PGz$QGz$RGz$DGz$z$YFz$SGz$SBz$TGz$UGz$VGz$cFz$dFz$z$YFz$ZFz$aFz$aFz$aFz$bFz$cFz$dFz$z$Pz$z$WGz$XGz$YGz$ZGz$aGz$QFz$HCz$bGz$cGz$dGz$eGz$fGz$gGz$hGz$iGz$jGz$kGz$lGz$GDz$mGz$nGz$oGz$pGz$qGz$rGz$sGz$tGz$uGz$vGz$z$mCz$z$YCz$ZCz$wGz$xGz$yGz$qCz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$GHz$xGz$HHz$IHz$Pz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$JHz$KHz$LHz$MHz$NHz$OHz$z$PHz$QHz$RHz$SHz$THz$UHz$VHz$WHz$XHz$YHz$uGz$vGz$z$kEz$ZHz$aHz$bHz$cHz$dHz$eHz$fHz$gHz$hHz$iHz$jHz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$kHz$lHz$mHz$wGz$xGz$nHz$IHz$Pz$z$oHz$pHz$UHz$VHz$WHz$XHz$YHz$uGz$vGz$z$kEz$ZHz$aHz$bHz$cHz$dHz$qHz$rHz$sHz$tHz$uHz$vHz$wHz$z$xHz$yHz$AIz$BIz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$CIz$DIz$EIz$FIz$SBz$GIz$HIz$iHz$IIz$JIz$KIz$z$kEz$lEz$z$LIz$MIz$NIz$OIz$PIz$uGz$vGz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$GHz$QIz$RIz$MIz$SIz$NHz$OHz$z$TIz$UIz$VIz$WIz$XIz$YIz$ZIz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$GHz$QIz$aIz$UIz$nHz$IHz$Pz$z$bIz$cIz$dIz$OIz$PIz$uGz$vGz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$GHz$QIz$eIz$cIz$fIz$NHz$OHz$z$TIz$gIz$hIz$iIz$jIz$kIz$lIz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$GHz$QIz$aIz$gIz$mIz$nIz$oIz$z$pIz$qIz$rIz$sIz$tIz$PIz$uGz$vGz$z$pIz$uIz$vIz$iIz$jIz$kIz$lIz$z$pIz$wIz$xIz$yIz$AJz$jIz$kIz$lIz$z$BJz$CJz$DJz$iIz$EJz$jIz$kIz$lIz$z$FJz$GJz$HJz$iIz$jIz$kIz$lIz$z$BJz$IJz$DJz$iIz$JJz$jIz$kIz$lIz$z$BJz$KJz$LJz$VIz$MJz$NJz$jIz$kIz$lIz$z$BJz$OJz$LJz$VIz$PJz$NJz$jIz$kIz$lIz$z$BJz$QJz$RJz$SJz$TJz$UJz$VJz$XIz$YIz$ZIz$z$pIz$WJz$XJz$lBz$YJz$ZJz$XIz$YIz$ZIz$z$pIz$aJz$bJz$lBz$cJz$dJz$eJz$fJz$gJz$z$pIz$hJz$iJz$jJz$kJz$lJz$lBz$jJz$kJz$lJz$PIz$uGz$vGz$z$pIz$mJz$nJz$OIz$PIz$uGz$vGz$z$pIz$uIz$vIz$iIz$jIz$kIz$lIz$z$pIz$oJz$pJz$lBz$dJz$eJz$fJz$gJz$z$pIz$qJz$rJz$VIz$WIz$XIz$YIz$ZIz$z$pIz$sJz$pJz$lBz$dJz$eJz$fJz$gJz$z$pIz$tJz$uJz$vJz$wJz$OIz$PIz$uGz$vGz$z$pIz$xJz$yJz$AKz$BKz$CKz$DKz$EKz$FKz$XIz$YIz$ZIz$z$xHz$yHz$z$oHz$GKz$yHz$AIz$BIz$z$oHz$HKz$iJz$IKz$z$fCz$gCz$AHz$BHz$CHz$DHz$EHz$FHz$JKz$KKz$SBz$LKz$Pz$z$MKz$NKz$OKz$PKz$QKz$RKz$SKz$TKz$UKz$VKz$WKz$XKz$YKz$z$ZKz$aKz$bKz$cKz$dKz$z$mCz$z$rCz$sCz$z$eKz$fKz$gKz$hKz$iKz$jKz$kKz$z$RHz$SHz$lKz$mKz$nKz$z$oKz$z$pKz$qKz$rKz$z$fCz$gCz$sKz$z$fCz$gCz$tKz$uKz$LHz$hJz$iJz$vHz$vKz$wKz$xKz$yKz$Pz$z$fCz$gCz$ALz$BLz$CLz$DLz$ELz$FLz$GLz$Pz$z$fCz$gCz$HLz$ILz$JLz$lFz$KLz$z$fCz$gCz$LLz$MLz$NLz$VHz$OLz$PLz$QLz$RLz$SLz$TLz$ULz$z$fCz$gCz$sKz$z$tCz$uCz$vCz$wCz$z$fCz$gCz$sKz$z$kEz$lEz$z$VLz$WLz$UHz$VHz$WHz$XLz$z$eKz$YLz$ZLz$aLz$bLz$uHz$cLz$z$fCz$gCz$dLz$eLz$fLz$gLz$hLz$iLz$jLz$kLz$lLz$z$mLz$nLz$oLz$z$pLz$qLz$SBz$rLz$eJz$fJz$sLz$tLz$z$uLz$z$fCz$gCz$vLz$wLz$xLz$yLz$AMz$BMz$CMz$DMz$EHz$Pz$z$fCz$gCz$EMz$FMz$NLz$VHz$OLz$PLz$ELz$FLz$GMz$z$fCz$gCz$sKz$z$MKz$HMz$IMz$aJz$JMz$KMz$vHz$QGz$BIz$z$LMz$MMz$NMz$OMz$PMz$OMz$QGz$QMz$RMz$kIz$lIz$SMz$TMz$UMz$z$eKz$YLz$ZLz$aLz$bLz$uHz$cLz$z$fCz$gCz$VMz$WMz$fLz$gLz$hLz$XMz$YMz$ZMz$aMz$bMz$cMz$dMz$eMz$z$mLz$nLz$oLz$z$pLz$qLz$SBz$rLz$eJz$fJz$sLz$tLz$z$uLz$z$fCz$gCz$vLz$wLz$xLz$yLz$fMz$gMz$dMz$eMz$z$fCz$gCz$hMz$vHz$iMz$jMz$kMz$lMz$mMz$nMz$oMz$pMz$qMz$NLz$rMz$OHz$z$oKz$z$uLz$z$fCz$gCz$vLz$sMz$tMz$uMz$vMz$wMz$lLz$z$fCz$gCz$xMz$yMz$ANz$tMz$uMz$BNz$VLz$nMz$oMz$pMz$qMz$NLz$rMz$CNz$DNz$ENz$FNz$z$oKz$z$oKz"
+RED='\033[0;31m'
+NC='\033[0m'
+gray="\e[1;30m"
+Blue="\033[0;34m"
+green='\033[0;32m'
+grenbo="\e[92;1m"
+YELL='\033[0;33m'
+BG_BLU="\033[44;1m" # BG BIRU
+MYIP=$(cat /usr/bin/ipsave)
+IP=$(wget -qO- icanhazip.com)
+dateToday=$(date +"%Y-%m-%d")
+Name=$(curl $(cat /etc/xray/license_server 2>/dev/null || echo "http://64.235.61.22:7888")/ip | grep $MYIP | awk '{print $2}')
+CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
+KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
+export TIME="10"
+export URL="https://api.telegram.org/bot$KEY/sendMessage"
+function baris_panjang() {
+echo -e "\033[5;36m ———————————————————————————————————————————————\033[0m"
+}
+function ARI_Banner() {
+clear
+baris_panjang
+NAMASC="Si Cepat VPN"
+function center_text() {
+local text="$1"
+local width=50  # Sesuaikan dengan panjang baris yang diinginkan
+local plain_text=$(echo -e "$text" | sed 's/\x1b\[[0-9;]*m//g')
+local len=${#plain_text}
+local spaces=$(( (width - len) / 2 ))
+printf "%${spaces}s%s\033[0m\n" "" "$(echo -e "$text")"
+}
+formatted_text="\e[36m.::.\033[0;35m $NAMASC \e[36m.::."
+center_text "$formatted_text"
+baris_panjang
+}
+function Sc_Credit() {
+sleep 1
+baris_panjang
+function center_text() {
+local text="$1"
+local width=50  # Sesuaikan dengan panjang baris yang diinginkan
+local plain_text=$(echo -e "$text" | sed 's/\x1b\[[0-9;]*m//g')
+local len=${#plain_text}
+local spaces=$(( (width - len) / 2 ))
+printf "%${spaces}s%s\033[0m\n" "" "$(echo -e "$text")"
+}
+formatted_text="\033[0;35m Terimakasih sudah menggunakan- \033[0m"
+formatted_text1="\033[0;35m Script Credit By $NAMASC \033[0m"
+center_text "$formatted_text"
+center_text "$formatted_text1"
+baris_panjang
+}
+function notif_restore() {
+sleep 2
+CHATID="$CHATID"
+KEY="$KEY"
+TIME="$TIME"
+URL="$URL"
+TEXT="
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>  ⚠️ RESTORE NOTIF⚠️</b>
+<b>     Detail Restore VPS</b>
+<code>◇━━━━━━━━━━━━━━◇</code>
+<b>USERNAME  : ${Name}</b>
+<b>DOMAIN    : ${domain}</b>
+<b>IP        : ${MYIP}</b>
+<b>TODAY     : ${dateToday}</b>
+<b>FILE      : ${filebackup}</b>
+<code>Restore Vps Done</code>
+<code>◇━━━━━━━━━━━━━━◇</code>
+"
+curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
+}
+function restoreBot() {
+echo -e "[ ${green}INFO${NC} ] • Restore Data..."
+echo -e "[ ${green}INFO${NC} ] • Getting your data..."
+7z x -p$InputPass /root/backup.zip &> /dev/null
+sleep 1  # Adding a delay for smoother process
+echo -e "[ ${green}INFO${NC} ] • Starting to restore data..."
+rm -f /root/backup.zip &> /dev/null
+sleep 1  # Adding a delay after removing the file
+cd /root/backup
+echo -e "[ ${green}INFO${NC} ] • Please Wait, Restoring In Process Now... "
+sleep 1
+cp passwd /etc/ &>/dev/null
+echo -e "[ ${green}INFO${NC} ] • Restoring passwd data..."
+cp group /etc/ &>/dev/null
+echo -e "[ ${green}INFO${NC} ] • Restoring group data..."
+cp shadow /etc/ &>/dev/null
+echo -e "[ ${green}INFO${NC} ] • Restoring shadow data..."
+cp gshadow /etc/ &>/dev/null
+echo -e "[ ${green}INFO${NC} ] • Restoring gshadow data..."
+cp -r kyt /var/lib/ &>/dev/null
+cp -r xray /etc/ &>/dev/null
+cp -r html /var/www/ &>/dev/null
+cp .bot.db /etc/bot/ &>/dev/null
+cp crontab /etc/ &>/dev/null
+cp .ssh.db /etc/ssh/ &>/dev/null
+cp .vmess.db /etc/vmess/ &>/dev/null
+cp .vless.db /etc/vless/ &>/dev/null
+cp .trojan.db /etc/trojan/ &>/dev/null
+cp -rf qt/* /etc/limit &>/dev/null
+cp -r limit /etc/kyt/ &>/dev/null
+cp -r backup/banner.txt /etc/banner.txt &>/dev/null
+cp -r ssh /etc/ &>/dev/null
+cp -r xray /etc/ &>/dev/null
+cp -r vmess /etc/ &>/dev/null
+cp -r trojan /etc/ &>/dev/null
+cp -r vless /etc/ &>/dev/null
+cp -r shadowsocks /etc/ &>/dev/null
+cp -r var.txt /usr/bin/kyt/var.txt &>/dev/null
+cd /root
+rm -rf /root/backup
+rm -f backup.zip
+echo -e "[ ${green}INFO${NC} ] • Done Restore..."
+read -n 1 -s -r -p " Press Enter for Back to Manage"
+bash /usr/bin/m-bkp
+}
+clear
+if [[ -z $InputPass ]]; then
+InputPass="Ari123Ok"
+fi
+ARI_Banner
+echo -e " "
+echo -e " Upload your backup file to a supported"
+echo -e " file hosting (direct link)"
+echo -e "      or        "
+echo -e " Send your backup file using Terminus App"
+echo -e " "
+baris_panjang
+echo -e " "
+sleep 1
+file="/root/backup.zip"
+if [[ -f "$file" ]]; then
+echo -e "${green}Backup File Detected${NC}"
+restoreBot
+notif_restore > /dev/null 2>&1
+else
+echo -e "${RED}Backup File Not Detected${NC}"
+echo -e "Enter your backup file direct link"
+echo -e " "
+read -p "Your link   : " filebackup
+if wget -O "$file" "$filebackup" > /dev/null 2>&1; then
+if [[ -f "$file" ]]; then
+echo -e "${GREEN}Backup File Downloaded Successfully${NC}"
+restoreBot
+notif_restore > /dev/null 2>&1
+else
+echo -e "${RED}Backup File Error${NC}"
+echo -e "The file was not downloaded. Please check your link."
+fi
+else
+echo -e "${RED}Download Error${NC}"
+echo -e "Failed to download the file. Please check your link and try again."
+fi
+fi
